// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"errors"
	"io"
	"net/http"

	"github.com/mockzilla/mockzilla-codegen/examples/layout/service-apart/models"
	"github.com/mockzilla/mockzilla-codegen/examples/layout/service-apart/service"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  service.ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc service.ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// CreateOrder handles POST /orders.
func (a *HTTPAdapter) CreateOrder(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "CreateOrder"))
	opts := &service.CreateOrderServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "CreateOrder", err)
			return
		}
	case "":
		a.failDecode(w, r, "CreateOrder", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "CreateOrder", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.CreateOrder(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "CreateOrder", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "CreateOrder", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "CreateOrder", res)
}

// GetOrder handles GET /orders/{id}.
func (a *HTTPAdapter) GetOrder(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetOrder"))
	opts := &service.GetOrderServiceRequestOptions{RawRequest: r}
	query := r.URL.Query()
	opts.PathParams = &models.GetOrderPathParams{}
	if err := runtime.DecodePath(r.PathValue("id"), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetOrder", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	opts.Query = &models.GetOrderQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "expand", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Expand); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetOrder", ParamName: "expand", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.GetOrder(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetOrder", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetOrder", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "GetOrder", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on mux instead of a new one.
func WithRouter(mux *http.ServeMux) ServerOption {
	return func(o *ServerOptions) {
		o.Router = mux
	}
}

// NewRouter registers every operation on an http.ServeMux.
func NewRouter(svc service.ServiceInterface, opts ...ServerOption) http.Handler {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(mux *http.ServeMux, route func(http.Handler) http.Handler) {
		mux.Handle("POST /orders", route(http.HandlerFunc(a.CreateOrder)))
		mux.Handle("GET /orders/{id}", route(http.HandlerFunc(a.GetOrder)))
	}

	if mux, _ := o.Router.(*http.ServeMux); mux != nil {
		register(mux, wrap)
		return mux
	}
	mux := http.NewServeMux()
	register(mux, func(h http.Handler) http.Handler { return h })
	return wrap(mux)
}
