// Code generated by mockzilla-codegen. DO NOT EDIT.

package enumnames

import "github.com/mockzilla/mockzilla-codegen/pkg/runtime"

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Priority int

const (
	PriorityLow    Priority = 0
	PriorityNormal Priority = 1
	PriorityUrgent Priority = 2
)

// Validate checks the value against the constraints of the spec.
func (p Priority) Validate() error {
	return runtime.OneOf(p, PriorityLow, PriorityNormal, PriorityUrgent)
}

type Region string

const (
	RegionEurope  Region = "eu-west-1"
	RegionAmerica Region = "us-east-1"
)

// Validate checks the value against the constraints of the spec.
func (r Region) Validate() error {
	return runtime.OneOf(r, RegionEurope, RegionAmerica)
}
