// Code generated by mockzilla-codegen. DO NOT EDIT.

package basic

import (
	"encoding/json"
	"net/http"

	chi "github.com/go-chi/chi/v5"
)

// Route is one routed operation of the API and the status of its success response.
type Route struct {
	ID     string
	Method string
	Path   string
	Status int
}

// Routes lists the routed operations of the API.
var Routes = []Route{
	{ID: "ListPets", Method: "GET", Path: "/pets", Status: 200},
	{ID: "CreatePet", Method: "POST", Path: "/pets", Status: 201},
	{ID: "DeletePet", Method: "DELETE", Path: "/pets/{id}", Status: 204},
	{ID: "Ping", Method: "GET", Path: "/ping", Status: 200},
}

// Register serves the list of routes at path on r.
func Register(r chi.Router, path string) {
	r.Get(path, func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(Routes)
	})
}
