// Code generated by mockzilla-codegen. DO NOT EDIT.

package basic

import "context"

// withBodies sets GenerateResponse on the options of an operation, then calls the service.
type withBodies struct {
	svc PetsInterface
}

// WithBodies returns svc with GenerateResponse set on the options of every operation.
func WithBodies(svc PetsInterface) PetsInterface {
	return &withBodies{svc: svc}
}

func (s *withBodies) ListPets(ctx context.Context, opts *ListPetsServiceRequestOptions) (*ListPetsResponseData, error) {
	opts.GenerateResponse = Bodies["ListPets"]
	return s.svc.ListPets(ctx, opts)
}

func (s *withBodies) CreatePet(ctx context.Context, opts *CreatePetServiceRequestOptions) (*CreatePetResponseData, error) {
	opts.GenerateResponse = Bodies["CreatePet"]
	return s.svc.CreatePet(ctx, opts)
}

func (s *withBodies) DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error) {
	opts.GenerateResponse = func() any { return nil }
	return s.svc.DeletePet(ctx, opts)
}

func (s *withBodies) Ping(ctx context.Context, opts *PingServiceRequestOptions) (*PingResponseData, error) {
	opts.GenerateResponse = Bodies["Ping"]
	return s.svc.Ping(ctx, opts)
}
