// Code generated by mockzilla-codegen. DO NOT EDIT.

package petstore

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpclient"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type NewPet struct {
	Name   string  `json:"name" db:"name"`
	Tag    *string `json:"tag,omitempty"`
	Status *Status `json:"status,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (n NewPet) Validate() error {
	var errs validation.Errors
	errs.Append("name", validation.MinLength(n.Name, 1))
	if n.Status != nil {
		errs.Append("status", n.Status.Validate())
	}
	return errs.Err()
}

type Pet struct {
	Name   string  `json:"name" db:"name"`
	Tag    *string `json:"tag,omitempty"`
	Status *Status `json:"status,omitempty"`
	ID     int64   `json:"id"`
}

// Validate checks the value against the constraints of the spec.
func (p Pet) Validate() error {
	var errs validation.Errors
	errs.Append("name", validation.MinLength(p.Name, 1))
	if p.Status != nil {
		errs.Append("status", p.Status.Validate())
	}
	return errs.Err()
}

type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Error returns the message at message.
func (e Error) Error() string {
	return runtime.ErrorMessage(e, "message", "Error")
}

// NewError returns a Error with message at message.
func NewError(message string) Error {
	var e Error
	_ = runtime.SetErrorMessage(&e, "message", message)
	return e
}

type Status string

const (
	StatusAvailable Status = "available"
	StatusPending   Status = "pending"
	StatusSold      Status = "sold"
)

// StatusValues returns the values of Status.
func StatusValues() []Status {
	return []Status{
		StatusAvailable,
		StatusPending,
		StatusSold,
	}
}

// Validate checks the value against the constraints of the spec.
func (s Status) Validate() error {
	return validation.Enum(s, StatusAvailable, StatusPending, StatusSold)
}

type ListPetsQuery struct {
	Limit  *int32  `json:"limit,omitempty"`
	Status *Status `json:"status,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (l ListPetsQuery) Validate() error {
	var errs validation.Errors
	if l.Limit != nil {
		errs.Append("limit", validation.Minimum(*l.Limit, 1, false))
	}
	if l.Status != nil {
		errs.Append("status", l.Status.Validate())
	}
	return errs.Err()
}

type GetPetPathParams struct {
	ID int64 `json:"id"`
}

type DeletePetPathParams struct {
	ID int64 `json:"id"`
}

type ListPetsResponse200 []Pet

// Validate checks the value against the constraints of the spec.
func (l ListPetsResponse200) Validate() error {
	var errs validation.Errors
	for idx, item := range l {
		errs.Append(validation.Index("", idx), item.Validate())
	}
	return errs.Err()
}

type CreatePetResponse201Headers struct {
	Location *string `json:"Location,omitempty"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// ListPets handles GET /pets.
	ListPets(ctx context.Context, opts *ListPetsServiceRequestOptions) (*ListPetsResponseData, error)
	// CreatePet handles POST /pets.
	CreatePet(ctx context.Context, opts *CreatePetServiceRequestOptions) (*CreatePetResponseData, error)
	// GetPet handles GET /pets/{id}.
	GetPet(ctx context.Context, opts *GetPetServiceRequestOptions) (*GetPetResponseData, error)
	// DeletePet handles DELETE /pets/{id}.
	DeletePet(ctx context.Context, opts *DeletePetServiceRequestOptions) (*DeletePetResponseData, error)
}

// ListPetsServiceRequestOptions is what ListPets receives.
type ListPetsServiceRequestOptions struct {
	Query      *ListPetsQuery
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListPetsServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// ListPetsResponseData is what ListPets returns.
type ListPetsResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewListPetsResponseData200 returns the 200 response with its application/json body.
func NewListPetsResponseData200(body ListPetsResponse200) *ListPetsResponseData {
	return &ListPetsResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewListPetsResponseDataDefault returns the default response with its application/json body.
func NewListPetsResponseDataDefault(status int, body *Error) *ListPetsResponseData {
	return &ListPetsResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *ListPetsResponseData) WithStatus(code int) *ListPetsResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ListPetsResponseData) WithHeaders(h http.Header) *ListPetsResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ListPetsResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ListPetsResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ListPetsResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *ListPetsResponseData) ContentType() string {
	return r.contentType
}

// CreatePetServiceRequestOptions is what CreatePet receives.
type CreatePetServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *NewPet
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CreatePetServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// CreatePetResponseData is what CreatePet returns.
type CreatePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewCreatePetResponseData201 returns the 201 response with its application/json body.
func NewCreatePetResponseData201(body *Pet) *CreatePetResponseData {
	return &CreatePetResponseData{Status: 201, Body: body, contentType: "application/json"}
}

// NewCreatePetResponseDataDefault returns the default response with its application/json body.
func NewCreatePetResponseDataDefault(status int, body *Error) *CreatePetResponseData {
	return &CreatePetResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *CreatePetResponseData) WithStatus(code int) *CreatePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *CreatePetResponseData) WithHeaders(h http.Header) *CreatePetResponseData {
	r.Headers = h
	return r
}

// WithTypedHeaders adds the headers the spec declares for status 201.
func (r *CreatePetResponseData) WithTypedHeaders(h CreatePetResponse201Headers) *CreatePetResponseData {
	r.Headers = runtime.Headers(r.Headers, h)
	return r
}

// StatusCode returns the status.
func (r *CreatePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *CreatePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *CreatePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *CreatePetResponseData) ContentType() string {
	return r.contentType
}

// GetPetServiceRequestOptions is what GetPet receives.
type GetPetServiceRequestOptions struct {
	PathParams *GetPetPathParams
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetServiceRequestOptions) Validate() error {
	return nil
}

// GetPetResponseData is what GetPet returns.
type GetPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetPetResponseData200 returns the 200 response with its application/json body.
func NewGetPetResponseData200(body *Pet) *GetPetResponseData {
	return &GetPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetPetResponseData404 returns the 404 response with its application/json body.
func NewGetPetResponseData404(body *Error) *GetPetResponseData {
	return &GetPetResponseData{Status: 404, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *GetPetResponseData) WithStatus(code int) *GetPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetPetResponseData) WithHeaders(h http.Header) *GetPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetPetResponseData) ContentType() string {
	return r.contentType
}

// DeletePetServiceRequestOptions is what DeletePet receives.
type DeletePetServiceRequestOptions struct {
	PathParams *DeletePetPathParams
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeletePetServiceRequestOptions) Validate() error {
	return nil
}

// DeletePetResponseData is what DeletePet returns.
type DeletePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewDeletePetResponseData returns the 204 response.
func NewDeletePetResponseData() *DeletePetResponseData {
	return &DeletePetResponseData{Status: 204, contentType: ""}
}

// WithStatus sets the status code.
func (r *DeletePetResponseData) WithStatus(code int) *DeletePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *DeletePetResponseData) WithHeaders(h http.Header) *DeletePetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *DeletePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *DeletePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *DeletePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *DeletePetResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       httpserver.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// ListPets handles GET /pets.
func (a *HTTPAdapter) ListPets(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "ListPets"))
	opts := &ListPetsServiceRequestOptions{RawRequest: r}
	query := runtime.ParseQuery(r.URL.RawQuery)
	opts.Query = &ListPetsQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "limit", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Limit); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "ListPets", ParamName: "limit", ParamLocation: "query", Err: err})
		return
	}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "status", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Status); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "ListPets", ParamName: "status", ParamLocation: "query", Err: err})
		return
	}

	res, err := a.svc.ListPets(r.Context(), opts)
	if err != nil {
		if e, ok := httpserver.AsError[Error](err); ok {
			w.Header().Set("Content-Type", "application/json")
			a.opts.ErrorHandler.HandleError(w, r, 500, e)
			return
		}
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListPets", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListPets", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "ListPets", res)
}

// CreatePet handles POST /pets.
func (a *HTTPAdapter) CreatePet(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "CreatePet"))
	opts := &CreatePetServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "CreatePet", err)
			return
		}
	case "":
		a.failDecode(w, r, "CreatePet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "CreatePet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.CreatePet(r.Context(), opts)
	if err != nil {
		if e, ok := httpserver.AsError[Error](err); ok {
			w.Header().Set("Content-Type", "application/json")
			a.opts.ErrorHandler.HandleError(w, r, 500, e)
			return
		}
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreatePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreatePet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "CreatePet", res)
}

// GetPet handles GET /pets/{id}.
func (a *HTTPAdapter) GetPet(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetPet"))
	opts := &GetPetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &GetPetPathParams{}
	if err := runtime.DecodePath(r.PathValue("id"), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetPet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetPet(r.Context(), opts)
	if err != nil {
		if e, ok := httpserver.AsError[Error](err); ok {
			w.Header().Set("Content-Type", "application/json")
			a.opts.ErrorHandler.HandleError(w, r, 404, e)
			return
		}
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetPet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetPet", res)
}

// DeletePet handles DELETE /pets/{id}.
func (a *HTTPAdapter) DeletePet(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "DeletePet"))
	opts := &DeletePetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &DeletePetPathParams{}
	if err := runtime.DecodePath(r.PathValue("id"), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "DeletePet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.DeletePet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "DeletePet", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "DeletePet", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	if body, mediaType := requestError(err); body != nil {
		err.Body = body
		w.Header().Set("Content-Type", mediaType)
	}
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

func requestError(err *httpserver.HandlerError) (error, string) {
	if err.Kind == httpserver.ErrorService || err.Kind == httpserver.ErrorResponse {
		return nil, ""
	}

	switch err.OperationID {
	case "ListPets", "CreatePet":
		return NewError(err.Error()), "application/json"
	}
	return nil, ""
}

// WithRouter registers the routes on mux instead of a new one.
func WithRouter(mux *http.ServeMux) ServerOption {
	return func(o *ServerOptions) {
		o.Router = mux
	}
}

// NewRouter registers every operation on an http.ServeMux.
func NewRouter(svc ServiceInterface, opts ...ServerOption) http.Handler {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(mux *http.ServeMux, route func(http.Handler) http.Handler) {
		mux.Handle("GET /pets", route(http.HandlerFunc(a.ListPets)))
		mux.Handle("POST /pets", route(http.HandlerFunc(a.CreatePet)))
		mux.Handle("GET /pets/{id}", route(http.HandlerFunc(a.GetPet)))
		mux.Handle("DELETE /pets/{id}", route(http.HandlerFunc(a.DeletePet)))
	}

	if mux, _ := o.Router.(*http.ServeMux); mux != nil {
		register(mux, wrap)
		return mux
	}
	mux := http.NewServeMux()
	register(mux, func(h http.Handler) http.Handler { return h })
	return wrap(mux)
}

// ListPetsRequestOptions is what ListPets sends.
type ListPetsRequestOptions struct {
	Query *ListPetsQuery
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListPetsRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// CreatePetRequestOptions is what CreatePet sends.
type CreatePetRequestOptions struct {
	// Body sent as application/json.
	Body *NewPet
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CreatePetRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// GetPetRequestOptions is what GetPet sends.
type GetPetRequestOptions struct {
	PathParams *GetPetPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetRequestOptions) Validate() error {
	return nil
}

// DeletePetRequestOptions is what DeletePet sends.
type DeletePetRequestOptions struct {
	PathParams *DeletePetPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeletePetRequestOptions) Validate() error {
	return nil
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = httpclient.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// ListPets calls GET /pets.
	ListPets(ctx context.Context, opts *ListPetsRequestOptions, editors ...RequestEditor) (ListPetsResponse200, error)
	// CreatePet calls POST /pets.
	CreatePet(ctx context.Context, opts *CreatePetRequestOptions, editors ...RequestEditor) (*Pet, error)
	// GetPet calls GET /pets/{id}.
	GetPet(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*Pet, error)
	// DeletePet calls DELETE /pets/{id}.
	DeletePet(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) error
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *httpclient.APIError.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := httpclient.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// ListPets calls GET /pets.
func (c *Client) ListPets(ctx context.Context, opts *ListPetsRequestOptions, editors ...RequestEditor) (ListPetsResponse200, error) {
	req, err := c.ListPetsRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := httpclient.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out ListPetsResponse200
	if err = httpclient.DecodeSuccess(res, body, []httpclient.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
		{Status: "default", MediaType: "application/json", Dst: new(Error)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// ListPetsRequest builds the request of GET /pets.
func (c *Client) ListPetsRequest(ctx context.Context, opts *ListPetsRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &ListPetsRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodGet, "/pets")
	if opts.Query != nil {
		b.QueryParam(opts.Query.Limit, runtime.Param{Name: "limit", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Status, runtime.Param{Name: "status", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false})
	}
	return c.newRequest(ctx, "ListPets", b, editors)
}

// CreatePet calls POST /pets.
func (c *Client) CreatePet(ctx context.Context, opts *CreatePetRequestOptions, editors ...RequestEditor) (*Pet, error) {
	req, err := c.CreatePetRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := httpclient.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Pet
	if err = httpclient.DecodeSuccess(res, body, []httpclient.ResponseTarget{
		{Status: "201", MediaType: "application/json", Dst: &out},
		{Status: "default", MediaType: "application/json", Dst: new(Error)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// CreatePetRequest builds the request of POST /pets.
func (c *Client) CreatePetRequest(ctx context.Context, opts *CreatePetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &CreatePetRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodPost, "/pets")
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json")
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "CreatePet", b, editors)
}

// GetPet calls GET /pets/{id}.
func (c *Client) GetPet(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*Pet, error) {
	req, err := c.GetPetRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := httpclient.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Pet
	if err = httpclient.DecodeSuccess(res, body, []httpclient.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
		{Status: "404", MediaType: "application/json", Dst: new(Error)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// GetPetRequest builds the request of GET /pets/{id}.
func (c *Client) GetPetRequest(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &GetPetRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodGet, "/pets/{id}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.ID, runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, "GetPet", b, editors)
}

// DeletePet calls DELETE /pets/{id}.
func (c *Client) DeletePet(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) error {
	req, err := c.DeletePetRequest(ctx, opts, editors...)
	if err != nil {
		return err
	}
	res, body, err := httpclient.Send(c.doer, req, "", c.timeout)
	if err != nil {
		return err
	}
	return httpclient.DecodeSuccess(res, body, nil)
}

// DeletePetRequest builds the request of DELETE /pets/{id}.
func (c *Client) DeletePetRequest(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &DeletePetRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodDelete, "/pets/{id}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.ID, runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, "DeletePet", b, editors)
}

func (c *Client) newRequest(ctx context.Context, id string, b *httpclient.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	ctx = runtime.WithOperationID(ctx, id)
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
