// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"context"
	"io"
	"net/http"

	"github.com/mockzilla/mockzilla-codegen/examples/server/iris/split/models"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime package does not match the codegen version that wrote this file.
const _ = runtime.SupportsGeneratorV2

// BooksInterface is what the generated handlers call. Implement it with the business logic.
type BooksInterface interface {
	GetBook(ctx context.Context, opts *GetBookServiceRequestOptions) (*GetBookResponseData, error)
}

// GetBookServiceRequestOptions is what GetBook receives. RawRequest is the request as it came in.
type GetBookServiceRequestOptions struct {
	PathParams *models.GetBookPathParams
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetBookServiceRequestOptions) Validate() error {
	return nil
}

// GetBookResponseData is what GetBook returns: the status, the headers and the body of the response.
type GetBookResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetBookResponseData200 returns the response data of status 200 with body as application/json.
func NewGetBookResponseData200(body *models.Book) *GetBookResponseData {
	return &GetBookResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetBookResponseData404 returns the response data of status 404 with body as application/json.
func NewGetBookResponseData404(body *models.Problem) *GetBookResponseData {
	return &GetBookResponseData{Status: 404, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *GetBookResponseData) WithStatus(code int) *GetBookResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetBookResponseData) WithHeaders(h http.Header) *GetBookResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetBookResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetBookResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetBookResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *GetBookResponseData) ContentType() string {
	return r.contentType
} // ServerOptions is what the adapter and the router are set up with. Router is the router the
// routes go on when one is given; Middleware wraps the routes, outermost first; ErrorHandler
// writes the response of a failed request; JSONDecoder reads JSON bodies.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first, after any middleware added before.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory before parts spill to
// disk.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service: one handler per operation.
type HTTPAdapter struct {
	svc  BooksInterface
	opts *ServerOptions
}

// responseData is what every response data type gives the adapter.
type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc BooksInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// GetBook handles GET /books/{isbn}.
func (a *HTTPAdapter) GetBook(w http.ResponseWriter, r *http.Request) {
	opts := &GetBookServiceRequestOptions{RawRequest: r}
	opts.PathParams = &models.GetBookPathParams{}
	if err := runtime.DecodePath(r.PathValue("isbn"), runtime.Param{Name: "isbn", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.Isbn); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetBook", ParamName: "isbn", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetBook(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetBook", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetBook", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "GetBook", res)
}

// fail answers a request the handler could not serve.
func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

// failDecode answers a request whose body could not be read.
func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

// write writes the response of the service.
func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	if err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}
