// Code generated by mockzilla-codegen. DO NOT EDIT.

package errors

import (
	"context"
	"errors"
	"io"
	"net/http"

	echo "github.com/labstack/echo/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Pet struct {
	Name string `json:"name"`
	Age  *int   `json:"age,omitempty"`
}

// Validate checks the value against the constraints of the spec, as a request carries it.
func (p Pet) Validate() error {
	var errs validation.Errors
	errs.Append("name", validation.MinLength(p.Name, 1))
	return errs.Err()
}

// ValidateResponse checks the value against the constraints of the spec, as a response carries it.
func (p Pet) ValidateResponse() error {
	var errs validation.Errors
	errs.Append("name", validation.MinLength(p.Name, 1))
	if p.Age != nil {
		errs.Append("age", validation.Minimum(*p.Age, 0, false))
	}
	return errs.Err()
}

type Problem struct {
	Detail string `json:"detail"`
}

// Error returns the message at detail.
func (p Problem) Error() string {
	return runtime.ErrorMessage(p, "detail", "Problem")
}

// NewProblem returns a Problem with message at detail.
func NewProblem(message string) Problem {
	var p Problem
	_ = runtime.SetErrorMessage(&p, "detail", message)
	return p
}

type Locked struct {
	Detail *string `json:"detail,omitempty"`
	Until  *string `json:"until,omitempty"`
}

type GetPetQueryFieldsItem string

const (
	GetPetQueryFieldsItemName GetPetQueryFieldsItem = "name"
	GetPetQueryFieldsItemAge  GetPetQueryFieldsItem = "age"
)

// GetPetQueryFieldsItemValues returns the values of GetPetQueryFieldsItem.
func GetPetQueryFieldsItemValues() []GetPetQueryFieldsItem {
	return []GetPetQueryFieldsItem{
		GetPetQueryFieldsItemName,
		GetPetQueryFieldsItemAge,
	}
}

// Validate checks the value against the constraints of the spec.
func (g GetPetQueryFieldsItem) Validate() error {
	return validation.Enum(g, GetPetQueryFieldsItemName, GetPetQueryFieldsItemAge)
}

type GetPetPathParams struct {
	ID int `json:"id"`
}

// Validate checks the value against the constraints of the spec.
func (g GetPetPathParams) Validate() error {
	var errs validation.Errors
	errs.Append("id", validation.Minimum(g.ID, 1, false))
	return errs.Err()
}

type GetPetQuery struct {
	Fields []GetPetQueryFieldsItem `json:"fields,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (g GetPetQuery) Validate() error {
	var errs validation.Errors
	for idx, item := range g.Fields {
		errs.Append(validation.Index("fields", idx), item.Validate())
	}
	return errs.Err()
}

type PutPetPathParams struct {
	ID int `json:"id"`
}

// Validate checks the value against the constraints of the spec.
func (p PutPetPathParams) Validate() error {
	var errs validation.Errors
	errs.Append("id", validation.Minimum(p.ID, 1, false))
	return errs.Err()
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// GetPet handles GET /pets/{id}.
	GetPet(ctx context.Context, opts *GetPetServiceRequestOptions) (*GetPetResponseData, error)
	// PutPet handles PUT /pets/{id}.
	PutPet(ctx context.Context, opts *PutPetServiceRequestOptions) (*PutPetResponseData, error)
}

// GetPetServiceRequestOptions is what GetPet receives.
type GetPetServiceRequestOptions struct {
	PathParams *GetPetPathParams
	Query      *GetPetQuery
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.PathParams != nil {
		errs.Append("path", o.PathParams.Validate())
	}
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// GetPetResponseData is what GetPet returns.
type GetPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetPetResponseData200 returns the 200 response with its application/json body.
func NewGetPetResponseData200(body *Pet) *GetPetResponseData {
	return &GetPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetPetResponseData404 returns the 404 response with its application/problem+json body.
func NewGetPetResponseData404(body *Problem) *GetPetResponseData {
	return &GetPetResponseData{Status: 404, Body: body, contentType: "application/problem+json"}
}

// NewGetPetResponseData409 returns the 409 response with its application/problem+json body.
func NewGetPetResponseData409(body *Locked) *GetPetResponseData {
	return &GetPetResponseData{Status: 409, Body: body, contentType: "application/problem+json"}
}

// WithStatus sets the status code.
func (r *GetPetResponseData) WithStatus(code int) *GetPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetPetResponseData) WithHeaders(h http.Header) *GetPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetPetResponseData) ContentType() string {
	return r.contentType
}

// PutPetServiceRequestOptions is what PutPet receives.
type PutPetServiceRequestOptions struct {
	PathParams *PutPetPathParams
	// Body sent as application/json.
	Body       *Pet
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PutPetServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.PathParams != nil {
		errs.Append("path", o.PathParams.Validate())
	}
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PutPetResponseData is what PutPet returns.
type PutPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPutPetResponseData200 returns the 200 response with its application/json body.
func NewPutPetResponseData200(body *Pet) *PutPetResponseData {
	return &PutPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewPutPetResponseData400 returns the 400 response with its application/problem+json body.
func NewPutPetResponseData400(body *Problem) *PutPetResponseData {
	return &PutPetResponseData{Status: 400, Body: body, contentType: "application/problem+json"}
}

// WithStatus sets the status code.
func (r *PutPetResponseData) WithStatus(code int) *PutPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PutPetResponseData) WithHeaders(h http.Header) *PutPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PutPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PutPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PutPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PutPetResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

var bodyPresence = runtime.Presence{
	IsChecked: true,
	Objects: []runtime.Object{
		{Name: "Pet", Props: []runtime.Prop{
			{Key: "age"},
			{Key: "name", IsRequired: true},
		}},
	},
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
	Presence           runtime.PresenceChecker
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
		Presence:           bodyPresence,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// WithPresence sets what checks the keys of request bodies and fills their defaults.
func WithPresence(p runtime.PresenceChecker) ServerOption {
	return func(o *ServerOptions) {
		o.Presence = p
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// GetPet handles GET /pets/{id}.
func (a *HTTPAdapter) GetPet(c *echo.Context) error {
	w, r := c.Response(), c.Request()
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetPet"))
	opts := &GetPetServiceRequestOptions{RawRequest: r}
	query := r.URL.Query()
	opts.PathParams = &GetPetPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, c.Param("id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetPet", ParamName: "id", ParamLocation: "path", Err: err})
		return nil
	}
	opts.Query = &GetPetQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "fields", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Fields); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetPet", ParamName: "fields", ParamLocation: "query", Err: err})
		return nil
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "GetPet", Err: err})
		return nil
	}

	res, err := a.svc.GetPet(r.Context(), opts)
	if err != nil {
		if e, ok := runtime.AsError[Problem](err); ok {
			w.Header().Set("Content-Type", "application/problem+json")
			a.opts.ErrorHandler.HandleError(w, r, 404, e)
			return nil
		}
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetPet", Err: err})
		return nil
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetPet", Err: runtime.ErrNoResponse})
		return nil
	}
	a.write(w, r, "GetPet", res)
	return nil
}

// PutPet handles PUT /pets/{id}.
func (a *HTTPAdapter) PutPet(c *echo.Context) error {
	w, r := c.Response(), c.Request()
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PutPet"))
	opts := &PutPetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &PutPetPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, c.Param("id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "PutPet", ParamName: "id", ParamLocation: "path", Err: err})
		return nil
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		body, err := a.opts.Presence.JSON(r.Body, runtime.Prop{Object: "Pet"})
		if err != nil {
			a.failBody(w, r, "PutPet", err)
			return nil
		}
		if err = a.opts.JSONDecoder(body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "PutPet", err)
			return nil
		}
	case "":
		a.failDecode(w, r, "PutPet", runtime.ErrBodyEmpty)
		return nil
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PutPet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return nil
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "PutPet", Err: err})
		return nil
	}

	res, err := a.svc.PutPet(r.Context(), opts)
	if err != nil {
		if e, ok := runtime.AsError[Problem](err); ok {
			w.Header().Set("Content-Type", "application/problem+json")
			a.opts.ErrorHandler.HandleError(w, r, 400, e)
			return nil
		}
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutPet", Err: err})
		return nil
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutPet", Err: runtime.ErrNoResponse})
		return nil
	}
	a.write(w, r, "PutPet", res)
	return nil
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	if body, mediaType := requestError(err); body != nil {
		err.Body = body
		w.Header().Set("Content-Type", mediaType)
	}
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) failBody(w http.ResponseWriter, r *http.Request, id string, err error) {
	kind := runtime.ErrorDecode
	if validation.Failed(err) {
		kind = runtime.ErrorValidation
	}
	a.fail(w, r, &runtime.HandlerError{Kind: kind, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if err := runtime.ValidateResponse(res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
		return
	}
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

func requestError(err *runtime.HandlerError) (error, string) {
	if err.Kind == runtime.ErrorService || err.Kind == runtime.ErrorResponse {
		return nil, ""
	}

	switch err.OperationID {
	case "PutPet":
		if err.StatusCode() == 400 {
			return NewProblem(err.Error()), "application/problem+json"
		}
	}
	return nil, ""
}

// WithRouter registers the routes on e instead of a new Echo.
func WithRouter(e *echo.Echo) ServerOption {
	return func(o *ServerOptions) {
		o.Router = e
	}
}

// NewRouter registers every operation on an Echo.
func NewRouter(svc ServiceInterface, opts ...ServerOption) *echo.Echo {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	middleware := make([]echo.MiddlewareFunc, len(o.Middleware))
	for i, mw := range o.Middleware {
		middleware[i] = echo.WrapMiddleware(mw)
	}
	register := func(e *echo.Echo, m ...echo.MiddlewareFunc) {
		e.GET("/pets/:id", a.GetPet, m...)
		e.PUT("/pets/:id", a.PutPet, m...)
	}

	e, _ := o.Router.(*echo.Echo)
	if e == nil {
		e = echo.New()
		if len(middleware) > 0 {
			e.Use(append(middleware, answerErrors)...)
		}
		register(e)
		return e
	}
	register(e, middleware...)
	return e
}

func answerErrors(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c *echo.Context) error {
		if err := next(c); err != nil {
			// Answered here, inside the middleware, so the middleware sees the response.
			c.Echo().HTTPErrorHandler(c, err)
		}
		return nil
	}
}
