// Code generated by mockzilla-codegen. DO NOT EDIT.

package checked

import (
	"context"
	"errors"
	"io"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Pet struct {
	Name  string   `json:"name"`
	Tag   *string  `json:"tag,omitempty"`
	Age   *int     `json:"age,omitempty"`
	Size  *string  `json:"size,omitempty"`
	Owner Owner    `json:"owner"`
	Tags  []string `json:"tags,omitempty"`
	Toys  []Toy    `json:"toys,omitempty"`
}

type Owner struct {
	ID   int     `json:"id"`
	City *string `json:"city,omitempty"`
}

type Toy struct {
	Name  string  `json:"name"`
	Color *string `json:"color,omitempty"`
}

type Upload struct {
	Photo runtime.File `json:"photo"`
	Note  *string      `json:"note,omitempty"`
}

type UploadResponse200 = string

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// AddPet handles POST /pets.
	AddPet(ctx context.Context, opts *AddPetServiceRequestOptions) (*AddPetResponseData, error)
	// Upload handles POST /uploads.
	Upload(ctx context.Context, opts *UploadServiceRequestOptions) (*UploadResponseData, error)
}

// AddPetServiceRequestOptions is what AddPet receives.
type AddPetServiceRequestOptions struct {
	// Body sent as application/json.
	BodyJSON *Pet
	// Body sent as application/x-www-form-urlencoded.
	BodyForm   *Pet
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AddPetServiceRequestOptions) Validate() error {
	return nil
}

// AddPetResponseData is what AddPet returns.
type AddPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewAddPetResponseData returns the 200 response with its application/json body.
func NewAddPetResponseData(body *Pet) *AddPetResponseData {
	return &AddPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *AddPetResponseData) WithStatus(code int) *AddPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *AddPetResponseData) WithHeaders(h http.Header) *AddPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *AddPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *AddPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *AddPetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *AddPetResponseData) ContentType() string {
	return r.contentType
}

// UploadServiceRequestOptions is what Upload receives.
type UploadServiceRequestOptions struct {
	// Body sent as multipart/form-data.
	Body       *Upload
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UploadServiceRequestOptions) Validate() error {
	return nil
}

// UploadResponseData is what Upload returns.
type UploadResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUploadResponseData returns the 200 response with its text/plain body.
func NewUploadResponseData(body *UploadResponse200) *UploadResponseData {
	return &UploadResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *UploadResponseData) WithStatus(code int) *UploadResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UploadResponseData) WithHeaders(h http.Header) *UploadResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UploadResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UploadResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UploadResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UploadResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

var requestBodies = runtime.Bodies{
	IsChecked: true,
	Objects: map[string]runtime.Object{
		"Owner": {Props: map[string]runtime.Prop{
			"city": {Default: `"Berlin"`},
			"id":   {IsRequired: true},
		}},
		"Pet": {IsClosed: true, Props: map[string]runtime.Prop{
			"age":   {Default: "1"},
			"name":  {IsRequired: true},
			"owner": {IsRequired: true, Object: "Owner"},
			"size":  {IsNullable: true, Default: `"m"`},
			"tag":   {IsNullable: true},
			"tags":  {Items: &runtime.Prop{}},
			"toys":  {Items: &runtime.Prop{Object: "Toy"}},
		}},
		"Toy": {Props: map[string]runtime.Prop{
			"color": {Default: `"red"`},
			"name":  {IsRequired: true},
		}},
		"Upload": {Props: map[string]runtime.Prop{
			"note":  {Default: `"none"`},
			"photo": {IsRequired: true},
		}},
	},
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// AddPet handles POST /pets.
func (a *HTTPAdapter) AddPet(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "AddPet"))
	opts := &AddPetServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		body, err := requestBodies.JSON(r.Body, runtime.Prop{Object: "Pet"})
		if err != nil {
			a.failBody(w, r, "AddPet", err)
			return
		}
		if err = a.opts.JSONDecoder(body, &opts.BodyJSON, true); err != nil {
			a.failDecode(w, r, "AddPet", err)
			return
		}
	case "application/x-www-form-urlencoded":
		body, err := requestBodies.Form(r.Body, runtime.Prop{Object: "Pet"})
		if err != nil {
			a.failBody(w, r, "AddPet", err)
			return
		}
		if err = runtime.DecodeForm(body, &opts.BodyForm, true); err != nil {
			a.failDecode(w, r, "AddPet", err)
			return
		}
	case "":
		a.failDecode(w, r, "AddPet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "AddPet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "AddPet", Err: err})
		return
	}

	res, err := a.svc.AddPet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "AddPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "AddPet", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "AddPet", res)
}

// Upload handles POST /uploads.
func (a *HTTPAdapter) Upload(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "Upload"))
	opts := &UploadServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "multipart/form-data":
		if err := requestBodies.Multipart(r, runtime.Prop{Object: "Upload"}, a.opts.MultipartMaxMemory); err != nil {
			a.failBody(w, r, "Upload", err)
			return
		}
		opts.Body = &Upload{}
		if err := runtime.DecodeMultipart(r, opts.Body, a.opts.MultipartMaxMemory); err != nil {
			a.failDecode(w, r, "Upload", err)
			return
		}
	case "":
		a.failDecode(w, r, "Upload", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "Upload", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "Upload", Err: err})
		return
	}

	res, err := a.svc.Upload(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Upload", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Upload", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "Upload", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) failBody(w http.ResponseWriter, r *http.Request, id string, err error) {
	kind := runtime.ErrorDecode
	if runtime.IsValidation(err) {
		kind = runtime.ErrorValidation
	}
	a.fail(w, r, &runtime.HandlerError{Kind: kind, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/pets", a.AddPet)
		r.Post("/uploads", a.Upload)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
