// Code generated by mockzilla-codegen. DO NOT EDIT.

package orders

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Status string

const (
	StatusOpen    Status = "open"
	StatusPaid    Status = "paid"
	StatusShipped Status = "shipped"
)

// StatusValues returns the values of Status.
func StatusValues() []Status {
	return []Status{
		StatusOpen,
		StatusPaid,
		StatusShipped,
	}
}

// Validate checks the value against the constraints of the spec.
func (s Status) Validate() error {
	return validation.Enum(s, StatusOpen, StatusPaid, StatusShipped)
}

type GetOrderQueryExpand string

const (
	GetOrderQueryExpandItems    GetOrderQueryExpand = "items"
	GetOrderQueryExpandCustomer GetOrderQueryExpand = "customer"
)

// GetOrderQueryExpandValues returns the values of GetOrderQueryExpand.
func GetOrderQueryExpandValues() []GetOrderQueryExpand {
	return []GetOrderQueryExpand{
		GetOrderQueryExpandItems,
		GetOrderQueryExpandCustomer,
	}
}

// Validate checks the value against the constraints of the spec.
func (g GetOrderQueryExpand) Validate() error {
	return validation.Enum(g, GetOrderQueryExpandItems, GetOrderQueryExpandCustomer)
}
