// Code generated by mockzilla-codegen. DO NOT EDIT.

package orders

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type GetOrderPathParams struct {
	ID string `json:"id"`
}

type GetOrderQuery struct {
	Expand *GetOrderQueryExpand `json:"expand,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (g GetOrderQuery) Validate() error {
	var errs validation.Errors
	if g.Expand != nil {
		errs.Append("expand", g.Expand.Validate())
	}
	return errs.Err()
}

type CreateOrderRequestBody struct {
	Items []Item `json:"items"`
}

// Validate checks the value against the constraints of the spec.
func (c CreateOrderRequestBody) Validate() error {
	var errs validation.Errors
	if c.Items == nil {
		errs.Required("items")
	}
	for idx, item := range c.Items {
		errs.Append(validation.Index("items", idx), item.Validate())
	}
	return errs.Err()
}
