// Code generated by mockzilla-codegen. DO NOT EDIT.

package orders

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Order struct {
	ID     string `json:"id"`
	Status Status `json:"status"`
	Items  []Item `json:"items,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (o Order) Validate() error {
	var errs validation.Errors
	errs.Append("status", o.Status.Validate())
	for idx, item := range o.Items {
		errs.Append(validation.Index("items", idx), item.Validate())
	}
	return errs.Err()
}

type Item struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

// Validate checks the value against the constraints of the spec.
func (i Item) Validate() error {
	var errs validation.Errors
	errs.Append("quantity", validation.Minimum(i.Quantity, 1, false))
	return errs.Err()
}

type Problem struct {
	Detail string `json:"detail"`
}
