// Code generated by mockzilla-codegen. DO NOT EDIT.

package bodies

import (
	"context"
	"io"
	"net/http"

	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/gogf/gf/v2/util/guid"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Note struct {
	Text  string `json:"text"`
	Stars *int   `json:"stars,omitempty"`
}

type UploadRequestBody struct {
	Title *string       `json:"title,omitempty"`
	File  *runtime.File `json:"file,omitempty"`
	Tags  []string      `json:"tags,omitempty"`
	Meta  *Note         `json:"meta,omitempty"`
}

type PostTextRequestBody = string

type PutFileRequestBody = runtime.File

type PostAnyXMLRequestBody = string

type PostAnyXMLRequestBody2 = string

type UploadResponse200 map[string]any

type PostTextResponse200 = string

type PutFileResponse200 = runtime.File

type PostAnyResponse200 = string

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// PostJSON handles POST /json.
	PostJSON(ctx context.Context, opts *PostJSONServiceRequestOptions) (*PostJSONResponseData, error)
	// PostForm handles POST /form.
	PostForm(ctx context.Context, opts *PostFormServiceRequestOptions) (*PostFormResponseData, error)
	// Upload handles POST /upload.
	Upload(ctx context.Context, opts *UploadServiceRequestOptions) (*UploadResponseData, error)
	// PostText handles POST /text.
	PostText(ctx context.Context, opts *PostTextServiceRequestOptions) (*PostTextResponseData, error)
	// PutFile handles PUT /file.
	PutFile(ctx context.Context, opts *PutFileServiceRequestOptions) (*PutFileResponseData, error)
	// PostAny handles POST /any.
	PostAny(ctx context.Context, opts *PostAnyServiceRequestOptions) (*PostAnyResponseData, error)
}

// PostJSONServiceRequestOptions is what PostJSON receives.
type PostJSONServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *Note
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostJSONServiceRequestOptions) Validate() error {
	return nil
}

// PostJSONResponseData is what PostJSON returns.
type PostJSONResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostJSONResponseData returns the 200 response with its application/json body.
func NewPostJSONResponseData(body *Note) *PostJSONResponseData {
	return &PostJSONResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostJSONResponseData) WithStatus(code int) *PostJSONResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostJSONResponseData) WithHeaders(h http.Header) *PostJSONResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostJSONResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostJSONResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostJSONResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostJSONResponseData) ContentType() string {
	return r.contentType
}

// PostFormServiceRequestOptions is what PostForm receives.
type PostFormServiceRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	Body       *Note
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostFormServiceRequestOptions) Validate() error {
	return nil
}

// PostFormResponseData is what PostForm returns.
type PostFormResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostFormResponseData returns the 200 response with its application/json body.
func NewPostFormResponseData(body *Note) *PostFormResponseData {
	return &PostFormResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostFormResponseData) WithStatus(code int) *PostFormResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostFormResponseData) WithHeaders(h http.Header) *PostFormResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostFormResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostFormResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostFormResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostFormResponseData) ContentType() string {
	return r.contentType
}

// UploadServiceRequestOptions is what Upload receives.
type UploadServiceRequestOptions struct {
	// Body sent as multipart/form-data.
	Body       *UploadRequestBody
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UploadServiceRequestOptions) Validate() error {
	return nil
}

// UploadResponseData is what Upload returns.
type UploadResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUploadResponseData returns the 200 response with its application/json body.
func NewUploadResponseData(body UploadResponse200) *UploadResponseData {
	return &UploadResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *UploadResponseData) WithStatus(code int) *UploadResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UploadResponseData) WithHeaders(h http.Header) *UploadResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UploadResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UploadResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UploadResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UploadResponseData) ContentType() string {
	return r.contentType
}

// PostTextServiceRequestOptions is what PostText receives.
type PostTextServiceRequestOptions struct {
	// Body sent as text/plain.
	BodyText *PostTextRequestBody
	// Body sent as application/octet-stream.
	BodyOctetStream []byte
	RawRequest      *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostTextServiceRequestOptions) Validate() error {
	return nil
}

// PostTextResponseData is what PostText returns.
type PostTextResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostTextResponseData returns the 200 response with its text/plain body.
func NewPostTextResponseData(body *PostTextResponse200) *PostTextResponseData {
	return &PostTextResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *PostTextResponseData) WithStatus(code int) *PostTextResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostTextResponseData) WithHeaders(h http.Header) *PostTextResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostTextResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostTextResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostTextResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostTextResponseData) ContentType() string {
	return r.contentType
}

// PutFileServiceRequestOptions is what PutFile receives.
type PutFileServiceRequestOptions struct {
	// Body sent as image/png.
	Body       *PutFileRequestBody
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PutFileServiceRequestOptions) Validate() error {
	return nil
}

// PutFileResponseData is what PutFile returns.
type PutFileResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPutFileResponseData returns the 200 response with its image/png body.
func NewPutFileResponseData(body *PutFileResponse200) *PutFileResponseData {
	return &PutFileResponseData{Status: 200, Body: body, contentType: "image/png"}
}

// WithStatus sets the status code.
func (r *PutFileResponseData) WithStatus(code int) *PutFileResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PutFileResponseData) WithHeaders(h http.Header) *PutFileResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PutFileResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PutFileResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PutFileResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PutFileResponseData) ContentType() string {
	return r.contentType
}

// PostAnyServiceRequestOptions is what PostAny receives.
type PostAnyServiceRequestOptions struct {
	// Body sent as application/xml.
	BodyXML *PostAnyXMLRequestBody
	// Body sent as text/xml.
	BodyTextXML *PostAnyXMLRequestBody2
	// Body sent as */*.
	BodyAny    []byte
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostAnyServiceRequestOptions) Validate() error {
	return nil
}

// PostAnyResponseData is what PostAny returns.
type PostAnyResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostAnyResponseData returns the 200 response with its text/plain body.
func NewPostAnyResponseData(body *PostAnyResponse200) *PostAnyResponseData {
	return &PostAnyResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *PostAnyResponseData) WithStatus(code int) *PostAnyResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostAnyResponseData) WithHeaders(h http.Header) *PostAnyResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostAnyResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostAnyResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostAnyResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostAnyResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 1048576,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// PostJSON handles POST /json.
func (a *HTTPAdapter) PostJSON(w http.ResponseWriter, r *http.Request) {
	opts := &PostJSONServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, false); err != nil {
			a.failDecode(w, r, "PostJSON", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostJSON", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostJSON(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostJSON", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostJSON", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostJSON", res)
}

// PostForm handles POST /form.
func (a *HTTPAdapter) PostForm(w http.ResponseWriter, r *http.Request) {
	opts := &PostFormServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "PostForm", err)
			return
		}
	case "":
		a.failDecode(w, r, "PostForm", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostForm", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostForm(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostForm", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostForm", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostForm", res)
}

// Upload handles POST /upload.
func (a *HTTPAdapter) Upload(w http.ResponseWriter, r *http.Request) {
	opts := &UploadServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "multipart/form-data":
		opts.Body = &UploadRequestBody{}
		if err := runtime.DecodeMultipart(r, opts.Body, a.opts.MultipartMaxMemory); err != nil {
			a.failDecode(w, r, "Upload", err)
			return
		}
	case "":
		a.failDecode(w, r, "Upload", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "Upload", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.Upload(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Upload", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Upload", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "Upload", res)
}

// PostText handles POST /text.
func (a *HTTPAdapter) PostText(w http.ResponseWriter, r *http.Request) {
	opts := &PostTextServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "text/plain":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostText", err)
			return
		}
		opts.BodyText = runtime.Ptr(PostTextRequestBody(text))
	case "application/octet-stream":
		data, err := runtime.DecodeBytes(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostText", err)
			return
		}
		opts.BodyOctetStream = data
	case "":
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostText", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostText(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostText", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostText", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostText", res)
}

// PutFile handles PUT /file.
func (a *HTTPAdapter) PutFile(w http.ResponseWriter, r *http.Request) {
	opts := &PutFileServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "image/png":
		file, err := runtime.DecodeFile(r, true)
		if err != nil {
			a.failDecode(w, r, "PutFile", err)
			return
		}
		opts.Body = runtime.Ptr(PutFileRequestBody(file))
	case "":
		a.failDecode(w, r, "PutFile", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PutFile", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PutFile(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutFile", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutFile", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PutFile", res)
}

// PostAny handles POST /any.
func (a *HTTPAdapter) PostAny(w http.ResponseWriter, r *http.Request) {
	opts := &PostAnyServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/xml":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyXML = runtime.Ptr(PostAnyXMLRequestBody(text))
	case "text/xml":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyTextXML = runtime.Ptr(PostAnyXMLRequestBody2(text))
	case "":
	default:
		data, err := runtime.DecodeBytes(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyAny = data
	}

	res, err := a.svc.PostAny(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostAny", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostAny", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostAny", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	if err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on s instead of a new Server.
func WithRouter(s *ghttp.Server) ServerOption {
	return func(o *ServerOptions) {
		o.Router = s
	}
}

// NewRouter registers every operation on a GoFrame server.
func NewRouter(svc ServiceInterface, opts ...ServerOption) *ghttp.Server {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(s *ghttp.Server, route func(http.Handler) http.Handler) {
		s.BindHandler("POST:/json", handle(route(http.HandlerFunc(adapter.PostJSON))))
		s.BindHandler("POST:/form", handle(route(http.HandlerFunc(adapter.PostForm))))
		s.BindHandler("POST:/upload", handle(route(http.HandlerFunc(adapter.Upload))))
		s.BindHandler("POST:/text", handle(route(http.HandlerFunc(adapter.PostText))))
		s.BindHandler("PUT:/file", handle(route(http.HandlerFunc(adapter.PutFile))))
		s.BindHandler("POST:/any", handle(route(http.HandlerFunc(adapter.PostAny))))
	}

	if s, _ := o.Router.(*ghttp.Server); s != nil {
		register(s, wrap)
		return s
	}
	// GoFrame keeps its servers by name, so a new one takes a fresh id.
	s := ghttp.GetServer(guid.S())
	register(s, wrap)
	s.BindStatusHandler(http.StatusNotFound, notFound(wrap(http.NotFoundHandler())))
	return s
}

func handle(h http.Handler) ghttp.HandlerFunc {
	return func(r *ghttp.Request) {
		for name, value := range r.GetRouterMap() {
			r.Request.SetPathValue(name, value)
		}
		// Past GoFrame's buffer, so a status without a body stays without one.
		h.ServeHTTP(r.Response.Writer, r.Request)
	}
}

func notFound(h http.Handler) ghttp.HandlerFunc {
	return func(r *ghttp.Request) {
		// GoFrame calls this for a 404 a route wrote too.
		if r.GetServeHandler() == nil {
			handle(h)(r)
		}
	}
}
