// Code generated by mockzilla-codegen. DO NOT EDIT.

package blocks

import (
	"context"
	"errors"
	"net/http"
)

// ErrNotImplemented is what every operation returns until it is written.
var ErrNotImplemented = errors.New("not implemented")

var _ PetsInterface = (*Pets)(nil)

// Pets implements PetsInterface.
type Pets struct{}

// NewPets returns a Pets.
func NewPets() *Pets {
	return &Pets{}
}

// ListPets handles GET /pets.
func (s *Pets) ListPets(ctx context.Context, opts *ListPetsServiceRequestOptions) (*ListPetsResponseData, error) {
	return &ListPetsResponseData{Status: http.StatusNotImplemented}, nil
}

// CreatePet handles POST /pets.
func (s *Pets) CreatePet(ctx context.Context, opts *CreatePetServiceRequestOptions) (*CreatePetResponseData, error) {
	return &CreatePetResponseData{Status: http.StatusNotImplemented}, nil
}
