// Code generated by mockzilla-codegen. DO NOT EDIT.

package orders

import (
	"context"
	"errors"

	"github.com/mockzilla/mockzilla-codegen/examples/layout/service-apart/service"
)

// ErrNotImplemented is what every operation returns until it is written.
var ErrNotImplemented = errors.New("not implemented")

var _ service.ServiceInterface = (*Service)(nil)

// Service implements service.ServiceInterface.
type Service struct{}

// NewService returns a Service.
func NewService() *Service {
	return &Service{}
}

// CreateOrder handles POST /orders.
func (s *Service) CreateOrder(ctx context.Context, opts *service.CreateOrderServiceRequestOptions) (*service.CreateOrderResponseData, error) {
	return nil, ErrNotImplemented
}

// GetOrder handles GET /orders/{id}.
func (s *Service) GetOrder(ctx context.Context, opts *service.GetOrderServiceRequestOptions) (*service.GetOrderResponseData, error) {
	return nil, ErrNotImplemented
}
