// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// WithRouter registers the routes on e instead of a new Engine.
func WithRouter(e *gin.Engine) ServerOption {
	return func(o *ServerOptions) {
		o.Router = e
	}
}

// NewRouter registers every operation on a gin Engine. On a new Engine the middleware
// WithMiddleware adds wraps everything, unknown paths too; on the Engine WithRouter gives it, the
// middleware wraps each generated route and nothing else.
func NewRouter(svc BooksInterface, opts ...ServerOption) *gin.Engine {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(e *gin.Engine, route func(http.Handler) http.Handler) {
		e.GET("/books/:isbn", handle(route(http.HandlerFunc(adapter.GetBook))))
	}

	if e, _ := o.Router.(*gin.Engine); e != nil {
		register(e, wrap)
		return e
	}
	e := gin.New()
	register(e, wrap)
	e.NoRoute(handle(wrap(http.NotFoundHandler())))
	return e
}

// handle serves h as a gin handler, with the path parameters gin found on the request.
func handle(h http.Handler) gin.HandlerFunc {
	return func(c *gin.Context) {
		for _, p := range c.Params {
			c.Request.SetPathValue(p.Key, p.Value)
		}
		h.ServeHTTP(c.Writer, c.Request)
	}
}
