// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)
