// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"errors"
	"net/http"
	"strings"

	fiber "github.com/gofiber/fiber/v3"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/valyala/fasthttp/fasthttpadaptor"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

// WithRouter registers the routes on app instead of a new App.
func WithRouter(app *fiber.App) ServerOption {
	return func(o *ServerOptions) {
		o.Router = app
	}
}

// WithConfig makes the new App with cfg.
func WithConfig(cfg fiber.Config) ServerOption {
	return func(o *ServerOptions) {
		o.Router = cfg
	}
}

// NewRouter registers every operation on a fiber App.
func NewRouter(svc BooksInterface, opts ...ServerOption) *fiber.App {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		// fasthttp would end the process on a panic.
		return runtime.Recover(h, o.ErrorHandler)
	}
	register := func(app *fiber.App, route func(http.Handler) http.Handler) {
		app.Get("/books/:isbn", handle(route(http.HandlerFunc(a.GetBook))))
	}

	if app, _ := o.Router.(*fiber.App); app != nil {
		register(app, wrap)
		return app
	}
	cfg, _ := o.Router.(fiber.Config)
	answer := cfg.ErrorHandler
	if answer == nil {
		answer = fiber.DefaultErrorHandler
	}
	notFound := handle(wrap(http.NotFoundHandler()))
	methodNotAllowed := handle(wrap(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusMethodNotAllowed)
	})))
	// Answered from the error handler, so that a route added later is still served.
	cfg.ErrorHandler = func(c fiber.Ctx, err error) error {
		var e *fiber.Error
		switch {
		case !errors.As(err, &e):
		case e.Code == fiber.StatusNotFound:
			return notFound(c)
		case e.Code == fiber.StatusMethodNotAllowed:
			return methodNotAllowed(c)
		}
		return answer(c, err)
	}
	app := fiber.New(cfg)
	register(app, wrap)
	return app
}

func handle(h http.Handler) fiber.Handler {
	return func(c fiber.Ctx) error {
		isEscaped := !c.App().Config().UnescapePath
		fasthttpadaptor.NewFastHTTPHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// fiber reuses the memory of the request's strings for the next request.
			r = runtime.DetachRequest(r)
			for _, name := range c.Route().Params {
				if isEscaped {
					r.SetPathValue(name, runtime.DetachPathValue(c.Params(name)))
				} else {
					r.SetPathValue(name, strings.Clone(c.Params(name)))
				}
			}
			h.ServeHTTP(w, r)
		}))(c.RequestCtx())
		return nil
	}
}
