// Code generated by mockzilla-codegen. DO NOT EDIT.

package discriminator

import (
	"encoding/json"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Card struct {
	Type   string `json:"type"`
	Number string `json:"number"`
}

type Bank struct {
	Type string `json:"type"`
	Iban string `json:"iban"`
}

type Wallet struct {
	Type     string  `json:"type"`
	Provider *string `json:"provider,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (w Wallet) Validate() error {
	var errs validation.Errors
	errs.Append("type", validation.Const(w.Type, "wallet"))
	return errs.Err()
}

type Unknown struct {
	Type *string `json:"type,omitempty"`
}

type InlineCircle struct {
	Kind   *string  `json:"kind,omitempty"`
	Radius *float64 `json:"radius,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (i InlineCircle) Validate() error {
	var errs validation.Errors
	if i.Kind != nil {
		errs.Append("kind", validation.Const(*i.Kind, "circle"))
	}
	return errs.Err()
}

type InlineSquare struct {
	Kind *string  `json:"kind,omitempty"`
	Side *float64 `json:"side,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (i InlineSquare) Validate() error {
	var errs validation.Errors
	if i.Kind != nil {
		errs.Append("kind", validation.Const(*i.Kind, "square"))
	}
	return errs.Err()
}

type Web struct {
	Host *string `json:"host,omitempty"`
}

type Shell struct {
	Key *string `json:"key,omitempty"`
}

type Secure struct {
	IsSecure *SecureIsSecure `json:"is_secure,omitempty"`
	Cert     *string         `json:"cert,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (s Secure) Validate() error {
	var errs validation.Errors
	if s.IsSecure != nil {
		errs.Append("is_secure", s.IsSecure.Validate())
	}
	return errs.Err()
}

type Plain struct {
	IsSecure *PlainIsSecure `json:"is_secure,omitempty"`
	Port     *int           `json:"port,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (p Plain) Validate() error {
	var errs validation.Errors
	if p.IsSecure != nil {
		errs.Append("is_secure", p.IsSecure.Validate())
	}
	return errs.Err()
}

type SecureIsSecure bool

const (
	SecureIsSecureTrue SecureIsSecure = true
)

// SecureIsSecureValues returns the values of SecureIsSecure.
func SecureIsSecureValues() []SecureIsSecure {
	return []SecureIsSecure{
		SecureIsSecureTrue,
	}
}

// Validate checks the value against the constraints of the spec.
func (s SecureIsSecure) Validate() error {
	return validation.Enum(s, SecureIsSecureTrue)
}

type PlainIsSecure bool

const (
	PlainIsSecureFalse PlainIsSecure = false
)

// PlainIsSecureValues returns the values of PlainIsSecure.
func PlainIsSecureValues() []PlainIsSecure {
	return []PlainIsSecure{
		PlainIsSecureFalse,
	}
}

// Validate checks the value against the constraints of the spec.
func (p PlainIsSecure) Validate() error {
	return validation.Enum(p, PlainIsSecureFalse)
}

// Explicit mapping for card, the implicit component name for Bank, a const for Wallet.
type Payment struct {
	Card   *Card   `json:"-"`
	Bank   *Bank   `json:"-"`
	Wallet *Wallet `json:"-"`
}

// MarshalJSON writes the variant that is set, with the discriminator value that picks it.
func (p Payment) MarshalJSON() ([]byte, error) {
	return runtime.MarshalVariants(nil, p.union(), p.Card, p.Bank, p.Wallet)
}

// UnmarshalJSON sets the variant data matches.
func (p *Payment) UnmarshalJSON(data []byte) error {
	*p = Payment{}
	return runtime.UnmarshalUnion(data, p.union())
}

func (p *Payment) union() runtime.Union {
	return runtime.Union{
		Discriminator: "type",
		Shared:        []string{"type"},
		Variants: []runtime.Variant{
			{
				Name:     "Card",
				Kind:     runtime.KindObject,
				Values:   []string{"card", "credit_card"},
				Required: []string{"type", "number"},
				Known:    []string{"type", "number"},
				Into:     runtime.Into(&p.Card),
			},
			{
				Name:     "Bank",
				Kind:     runtime.KindObject,
				Values:   []string{"Bank"},
				Required: []string{"type", "iban"},
				Known:    []string{"type", "iban"},
				Into:     runtime.Into(&p.Bank),
			},
			{
				Name:     "Wallet",
				Kind:     runtime.KindObject,
				Values:   []string{"wallet"},
				Required: []string{"type"},
				Known:    []string{"type", "provider"},
				Into:     runtime.Into(&p.Wallet),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (p Payment) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(p.Card != nil, p.Bank != nil, p.Wallet != nil))
	errs.Append("", runtime.DiscriminatorError(p.MarshalJSON()))
	if p.Wallet != nil {
		errs.Append("", p.Wallet.Validate())
	}
	return errs.Err()
}

// Any other type value falls back to Unknown.
type Tolerant struct {
	Card    *Card    `json:"-"`
	Unknown *Unknown `json:"-"`
}

// MarshalJSON writes the variant that is set, with the discriminator value that picks it.
func (t Tolerant) MarshalJSON() ([]byte, error) {
	return runtime.MarshalVariants(nil, t.union(), t.Card, t.Unknown)
}

// UnmarshalJSON sets the variant data matches.
func (t *Tolerant) UnmarshalJSON(data []byte) error {
	*t = Tolerant{}
	return runtime.UnmarshalUnion(data, t.union())
}

func (t *Tolerant) union() runtime.Union {
	return runtime.Union{
		Discriminator: "type",
		Shared:        []string{"type"},
		Variants: []runtime.Variant{
			{
				Name:     "Card",
				Kind:     runtime.KindObject,
				Values:   []string{"card"},
				Required: []string{"type", "number"},
				Known:    []string{"type", "number"},
				Into:     runtime.Into(&t.Card),
			},
			{
				Name:      "Unknown",
				Kind:      runtime.KindObject,
				Values:    []string{"Unknown"},
				IsDefault: true,
				Known:     []string{"type"},
				Into:      runtime.Into(&t.Unknown),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (t Tolerant) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(t.Card != nil, t.Unknown != nil))
	errs.Append("", runtime.DiscriminatorError(t.MarshalJSON()))
	return errs.Err()
}

// Inline is one of Circle or Square.
type Inline struct {
	Circle *InlineCircle `json:"-"`
	Square *InlineSquare `json:"-"`
}

// MarshalJSON writes the variant that is set, with the discriminator value that picks it.
func (i Inline) MarshalJSON() ([]byte, error) {
	return runtime.MarshalVariants(nil, i.union(), i.Circle, i.Square)
}

// UnmarshalJSON sets the variant data matches.
func (i *Inline) UnmarshalJSON(data []byte) error {
	*i = Inline{}
	return runtime.UnmarshalUnion(data, i.union())
}

func (i *Inline) union() runtime.Union {
	return runtime.Union{
		Discriminator: "kind",
		Shared:        []string{"kind"},
		Variants: []runtime.Variant{
			{
				Name:   "Circle",
				Kind:   runtime.KindObject,
				Values: []string{"circle"},
				Known:  []string{"kind", "radius"},
				Into:   runtime.Into(&i.Circle),
			},
			{
				Name:   "Square",
				Kind:   runtime.KindObject,
				Values: []string{"square"},
				Known:  []string{"kind", "side"},
				Into:   runtime.Into(&i.Square),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (i Inline) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(i.Circle != nil, i.Square != nil))
	errs.Append("", runtime.DiscriminatorError(i.MarshalJSON()))
	if i.Circle != nil {
		errs.Append("", i.Circle.Validate())
	}
	if i.Square != nil {
		errs.Append("", i.Square.Validate())
	}
	return errs.Err()
}

// Two values pick Web, which has no server_type, so the union keeps the value.
type Server struct {
	ServerType *string `json:"server_type,omitempty"`
	Web        *Web    `json:"-"`
	Shell      *Shell  `json:"-"`
}

// MarshalJSON writes the variant that is set, with the discriminator value that picks it.
func (s Server) MarshalJSON() ([]byte, error) {
	type plain Server
	return runtime.MarshalVariants(plain(s), s.union(), s.Web, s.Shell)
}

// UnmarshalJSON sets the variant data matches, and the shared properties.
func (s *Server) UnmarshalJSON(data []byte) error {
	*s = Server{}
	type plain Server
	if err := json.Unmarshal(data, (*plain)(s)); err != nil {
		return err
	}
	return runtime.UnmarshalUnion(data, s.union())
}

func (s *Server) union() runtime.Union {
	return runtime.Union{
		Discriminator: "server_type",
		Shared:        []string{"server_type"},
		Variants: []runtime.Variant{
			{
				Name:   "Web",
				Kind:   runtime.KindObject,
				Values: []string{"nginx", "apache"},
				Known:  []string{"host"},
				Into:   runtime.Into(&s.Web),
			},
			{
				Name:   "Shell",
				Kind:   runtime.KindObject,
				Values: []string{"shell"},
				Known:  []string{"key"},
				Into:   runtime.Into(&s.Shell),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (s Server) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(s.Web != nil, s.Shell != nil))
	errs.Append("", runtime.DiscriminatorError(s.MarshalJSON()))
	return errs.Err()
}

// A boolean property is no discriminator, so the enums pick the variant.
type Connection struct {
	Secure *Secure `json:"-"`
	Plain  *Plain  `json:"-"`
}

// MarshalJSON writes the variant that is set.
func (c Connection) MarshalJSON() ([]byte, error) {
	var set []any
	if c.Secure != nil {
		set = append(set, c.Secure)
	}
	if c.Plain != nil {
		set = append(set, c.Plain)
	}
	return runtime.MarshalOneOf(nil, set...)
}

// UnmarshalJSON sets the variant data matches.
func (c *Connection) UnmarshalJSON(data []byte) error {
	*c = Connection{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Variants: []runtime.Variant{
			{
				Name:  "Secure",
				Kind:  runtime.KindObject,
				Known: []string{"is_secure", "cert"},
				Into:  runtime.Into(&c.Secure),
			},
			{
				Name:  "Plain",
				Kind:  runtime.KindObject,
				Known: []string{"is_secure", "port"},
				Into:  runtime.Into(&c.Plain),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (c Connection) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(c.Secure != nil, c.Plain != nil))
	if c.Secure != nil {
		errs.Append("", c.Secure.Validate())
	}
	if c.Plain != nil {
		errs.Append("", c.Plain.Validate())
	}
	return errs.Err()
}
