// Code generated by mockzilla-codegen. DO NOT EDIT.

package discriminator

import "github.com/mockzilla/mockzilla-codegen/pkg/runtime"

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Card struct {
	Type   string `json:"type"`
	Number string `json:"number"`
}

type Bank struct {
	Type string `json:"type"`
	Iban string `json:"iban"`
}

type Wallet struct {
	Type     string  `json:"type"`
	Provider *string `json:"provider,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (w Wallet) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("type", runtime.Const(w.Type, "wallet"))
	return errs.Err()
}

type Unknown struct {
	Type *string `json:"type,omitempty"`
}

type InlineCircle struct {
	Kind   *string  `json:"kind,omitempty"`
	Radius *float64 `json:"radius,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (i InlineCircle) Validate() error {
	var errs runtime.ValidationErrors
	if i.Kind != nil {
		errs.Append("kind", runtime.Const(*i.Kind, "circle"))
	}
	return errs.Err()
}

type InlineSquare struct {
	Kind *string  `json:"kind,omitempty"`
	Side *float64 `json:"side,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (i InlineSquare) Validate() error {
	var errs runtime.ValidationErrors
	if i.Kind != nil {
		errs.Append("kind", runtime.Const(*i.Kind, "square"))
	}
	return errs.Err()
}

// Explicit mapping for card, the implicit component name for Bank, a const for Wallet.
type Payment struct {
	Card   *Card   `json:"-"`
	Bank   *Bank   `json:"-"`
	Wallet *Wallet `json:"-"`
}

// MarshalJSON writes the variants that are set.
func (p Payment) MarshalJSON() ([]byte, error) {
	var set []any
	if p.Card != nil {
		set = append(set, p.Card)
	}
	if p.Bank != nil {
		set = append(set, p.Bank)
	}
	if p.Wallet != nil {
		set = append(set, p.Wallet)
	}
	return runtime.MarshalUnion(nil, set...)
}

// UnmarshalJSON sets the variants data matches.
func (p *Payment) UnmarshalJSON(data []byte) error {
	*p = Payment{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Discriminator: "type",
		Shared:        []string{"type"},
		Variants: []runtime.Variant{
			{
				Name:     "Card",
				Kind:     runtime.KindObject,
				Values:   []string{"card", "credit_card"},
				Required: []string{"type", "number"},
				Known:    []string{"type", "number"},
				Into:     runtime.Into(&p.Card),
			},
			{
				Name:     "Bank",
				Kind:     runtime.KindObject,
				Values:   []string{"Bank"},
				Required: []string{"type", "iban"},
				Known:    []string{"type", "iban"},
				Into:     runtime.Into(&p.Bank),
			},
			{
				Name:     "Wallet",
				Kind:     runtime.KindObject,
				Values:   []string{"wallet"},
				Required: []string{"type"},
				Known:    []string{"type", "provider"},
				Into:     runtime.Into(&p.Wallet),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (p Payment) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.ExactlyOne(p.Card != nil, p.Bank != nil, p.Wallet != nil))
	if p.Wallet != nil {
		errs.Append("", p.Wallet.Validate())
	}
	return errs.Err()
}

// Any other type value falls back to Unknown.
type Tolerant struct {
	Card    *Card    `json:"-"`
	Unknown *Unknown `json:"-"`
}

// MarshalJSON writes the variants that are set.
func (t Tolerant) MarshalJSON() ([]byte, error) {
	var set []any
	if t.Card != nil {
		set = append(set, t.Card)
	}
	if t.Unknown != nil {
		set = append(set, t.Unknown)
	}
	return runtime.MarshalUnion(nil, set...)
}

// UnmarshalJSON sets the variants data matches.
func (t *Tolerant) UnmarshalJSON(data []byte) error {
	*t = Tolerant{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Discriminator: "type",
		Shared:        []string{"type"},
		Variants: []runtime.Variant{
			{
				Name:     "Card",
				Kind:     runtime.KindObject,
				Values:   []string{"card"},
				Required: []string{"type", "number"},
				Known:    []string{"type", "number"},
				Into:     runtime.Into(&t.Card),
			},
			{
				Name:      "Unknown",
				Kind:      runtime.KindObject,
				Values:    []string{"Unknown"},
				IsDefault: true,
				Known:     []string{"type"},
				Into:      runtime.Into(&t.Unknown),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (t Tolerant) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.ExactlyOne(t.Card != nil, t.Unknown != nil))
	return errs.Err()
}

type Inline struct {
	Circle *InlineCircle `json:"-"`
	Square *InlineSquare `json:"-"`
}

// MarshalJSON writes the variants that are set.
func (i Inline) MarshalJSON() ([]byte, error) {
	var set []any
	if i.Circle != nil {
		set = append(set, i.Circle)
	}
	if i.Square != nil {
		set = append(set, i.Square)
	}
	return runtime.MarshalUnion(nil, set...)
}

// UnmarshalJSON sets the variants data matches.
func (i *Inline) UnmarshalJSON(data []byte) error {
	*i = Inline{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Discriminator: "kind",
		Shared:        []string{"kind"},
		Variants: []runtime.Variant{
			{
				Name:   "Circle",
				Kind:   runtime.KindObject,
				Values: []string{"circle"},
				Known:  []string{"kind", "radius"},
				Into:   runtime.Into(&i.Circle),
			},
			{
				Name:   "Square",
				Kind:   runtime.KindObject,
				Values: []string{"square"},
				Known:  []string{"kind", "side"},
				Into:   runtime.Into(&i.Square),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (i Inline) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.ExactlyOne(i.Circle != nil, i.Square != nil))
	if i.Circle != nil {
		errs.Append("", i.Circle.Validate())
	}
	if i.Square != nil {
		errs.Append("", i.Square.Validate())
	}
	return errs.Err()
}
