// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"io"
	"net/http"
	"strings"

	"github.com/beego/beego/v2/server/web"
	bcontext "github.com/beego/beego/v2/server/web/context"
)

// WithRouter registers the routes on r instead of a new ControllerRegister.
func WithRouter(r *web.ControllerRegister) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a beego ControllerRegister.
func NewRouter(svc BooksInterface, opts ...ServerOption) *web.ControllerRegister {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(r *web.ControllerRegister, route func(http.Handler) http.Handler) {
		r.AddMethod("GET", "/books/:isbn", handle(route(http.HandlerFunc(a.GetBook))))
	}

	if r, _ := o.Router.(*web.ControllerRegister); r != nil {
		register(r, wrap)
		return r
	}
	r := web.NewControllerRegister()
	register(r, wrap)
	r.Any("/*", handle(wrap(http.NotFoundHandler())))
	return r
}

func handle(h http.Handler) web.HandleFunc {
	return func(c *bcontext.Context) {
		r := c.Request
		for key, value := range c.Input.Params() {
			if len(key) > 1 && key[0] == ':' {
				r.SetPathValue(key[1:], value)
			}
		}
		// beego has read the form body of these methods, so it goes back for h.
		isRead := r.Method == http.MethodPost || r.Method == http.MethodPut || r.Method == http.MethodPatch
		if isRead && r.PostForm != nil && strings.HasPrefix(r.Header.Get("Content-Type"), "application/x-www-form-urlencoded") {
			r.Body = io.NopCloser(strings.NewReader(r.PostForm.Encode()))
		}
		h.ServeHTTP(c.ResponseWriter, r)
	}
}
