// Code generated by mockzilla-codegen. DO NOT EDIT.

package streaming

import (
	"context"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime package does not match the mockzilla-codegen version that
// wrote this file.
const _ = runtime.SupportsGeneratorV2

type Prompt struct {
	Text   string `json:"text"`
	Stream *bool  `json:"stream,omitempty"`
}

type Reply struct {
	Text string `json:"text"`
}

type Chunk struct {
	Text string `json:"text"`
	Done *bool  `json:"done,omitempty"`
}

type Problem struct {
	Detail string `json:"detail"`
}

// Error returns the message at detail.
func (p Problem) Error() string {
	return runtime.ErrorMessage(p, "detail", "Problem")
}

// NewProblem returns a Problem with message at detail.
func NewProblem(message string) Problem {
	var p Problem
	_ = runtime.SetErrorMessage(&p, "detail", message)
	return p
}

type ListEventsResponseItemKind string

const (
	ListEventsResponseItemKindCreated ListEventsResponseItemKind = "created"
	ListEventsResponseItemKindDeleted ListEventsResponseItemKind = "deleted"
)

// Validate checks the value against the constraints of the spec.
func (l ListEventsResponseItemKind) Validate() error {
	return runtime.OneOf(l, ListEventsResponseItemKindCreated, ListEventsResponseItemKindDeleted)
}

type TailLogPathParams struct {
	Job string `json:"job"`
}

type ChatResponse200Headers struct {
	XModel *string `json:"X-Model,omitempty"`
}

type ListEventsResponseItem struct {
	Seq   int                          `json:"seq"`
	Kind  ListEventsResponseItemKind   `json:"kind"`
	At    *time.Time                   `json:"at,omitempty"`
	Actor *ListEventsResponseItemActor `json:"actor,omitempty"`
	Tags  []string                     `json:"tags,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (l ListEventsResponseItem) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("kind", l.Kind.Validate())
	return errs.Err()
}

type ListEventsResponseItemActor struct {
	Name string `json:"name"`
}

type TailLogResponseItem = string

// ChatRequestOptions is what Chat sends: its parameters by location, and its body.
type ChatRequestOptions struct {
	// Body sent as application/json.
	Body *Prompt
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ChatRequestOptions) Validate() error {
	return nil
}

// ListEventsRequestOptions is what ListEvents sends: its parameters by location, and its body.
type ListEventsRequestOptions struct {
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListEventsRequestOptions) Validate() error {
	return nil
}

// TailLogRequestOptions is what TailLog sends: its parameters by location, and its body.
type TailLogRequestOptions struct {
	PathParams *TailLogPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *TailLogRequestOptions) Validate() error {
	return nil
}

// ChatResponse is what ChatWithResponse returns: the response with its body read, and the body
// decoded into the field of its status and media type. ChatStreamWithResponse leaves the
// body of a streamed response unread, in the stream field.
type ChatResponse struct {
	HTTPResponse *http.Response
	Body         []byte
	// JSON200 is the body of a 200 response as application/json.
	JSON200 *Reply
	// EventStream200 is the body of a 200 response as text/event-stream.
	EventStream200 *string
	// ProblemJSON400 is the body of a 400 response as application/problem+json.
	ProblemJSON400 *Problem
	// Stream200 is the stream of a 200 response as text/event-stream, set by the Stream method alone;
	// Body is nil then.
	Stream200 *runtime.Stream[Chunk]
	// Headers200 holds the headers the spec declares for a 200 response.
	Headers200 *ChatResponse200Headers
}

// StatusCode is the status of the response.
func (r *ChatResponse) StatusCode() int {
	return r.HTTPResponse.StatusCode
}

// ListEventsResponse is what ListEventsWithResponse returns: the response with its body read, and the body
// decoded into the field of its status and media type. ListEventsStreamWithResponse leaves the
// body of a streamed response unread, in the stream field.
type ListEventsResponse struct {
	HTTPResponse *http.Response
	Body         []byte
	// Stream200 is the stream of a 200 response as text/event-stream, set by the Stream method alone;
	// Body is nil then.
	Stream200 *runtime.Stream[ListEventsResponseItem]
}

// StatusCode is the status of the response.
func (r *ListEventsResponse) StatusCode() int {
	return r.HTTPResponse.StatusCode
}

// TailLogResponse is what TailLogWithResponse returns: the response with its body read, and the body
// decoded into the field of its status and media type. TailLogStreamWithResponse leaves the
// body of a streamed response unread, in the stream field.
type TailLogResponse struct {
	HTTPResponse *http.Response
	Body         []byte
	// Ndjson200 is the body of a 200 response as application/x-ndjson.
	Ndjson200 *TailLogResponseItem
	// ProblemJSON404 is the body of a 404 response as application/problem+json.
	ProblemJSON404 *Problem
	// Stream200 is the stream of a 200 response as application/x-ndjson, set by the Stream method
	// alone; Body is nil then.
	Stream200 *runtime.Stream[[]byte]
}

// StatusCode is the status of the response.
func (r *TailLogResponse) StatusCode() int {
	return r.HTTPResponse.StatusCode
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent, to add credentials for one.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements: one method per operation, so a test double can
// stand in for the client.
type ClientInterface interface {
	// Chat calls POST /chat.
	//
	// Ask the assistant
	//
	// Answers whole as JSON, or as a stream of chunks when the prompt asks for one.
	Chat(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*Reply, error)
	ChatWithResponse(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*ChatResponse, error)
	ChatStream(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*runtime.Stream[Chunk], error)
	ChatStreamWithResponse(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*ChatResponse, error)
	// ListEvents calls GET /events.
	//
	// Follow the events
	ListEvents(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) error
	ListEventsWithResponse(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*ListEventsResponse, error)
	ListEventsStream(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*runtime.Stream[ListEventsResponseItem], error)
	ListEventsStreamWithResponse(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*ListEventsResponse, error)
	// TailLog calls GET /logs/{job}.
	//
	// Follow the log of a job
	TailLog(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponseItem, error)
	TailLogWithResponse(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponse, error)
	TailLogStream(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*runtime.Stream[[]byte], error)
	TailLogStreamWithResponse(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponse, error)
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d, such as an http.Client set up for the API. A nil d
// panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit. A Stream method waits that long for
// the response headers only, then reads frames until the server ends the stream or the context
// is canceled. An http.Client with a Timeout cuts the stream after it.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent, after any editor added before
// and before the editors of the call. A nil editor panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL, with one method per operation.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL. It sends with an http.Client unless
// WithHTTPClient sets another. A call gives up after 3 * time.Second unless WithTimeout
// sets another limit.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// Chat calls POST /chat.
//
// # Ask the assistant
//
// Answers whole as JSON, or as a stream of chunks when the prompt asks for one.
//
// It returns the body of a 200 response. A response outside 2xx, or a 2xx the spec does
// not list, comes back as a *runtime.APIError, wrapping the error type of its status when the spec
// documents one.
func (c *Client) Chat(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*Reply, error) {
	req, err := c.ChatRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Reply
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
		{Status: "400", MediaType: "application/problem+json", Dst: new(Problem)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// ChatWithResponse is Chat with the whole response: its status, its headers, its raw
// body, and the body decoded into the field of its status and media type. A status outside 2xx is
// no error here. A body or header that does not decode is an error, returned with the response.
func (c *Client) ChatWithResponse(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*ChatResponse, error) {
	req, err := c.ChatRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	out := &ChatResponse{HTTPResponse: res, Body: body}
	if err = runtime.Decode(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out.JSON200},
		{Status: "200", MediaType: "text/event-stream", Dst: &out.EventStream200},
		{Status: "400", MediaType: "application/problem+json", Dst: &out.ProblemJSON400},
		{Status: "200", IsHeaders: true, Dst: &out.Headers200},
	}); err != nil {
		return out, err
	}
	return out, nil
}

// ChatStream is Chat over a live stream: it asks for text/event-stream and returns the
// frames of a 2xx response in a sequential media type as they arrive. The caller closes the stream.
// Any other 2xx response is runtime.ErrContentType; a response outside 2xx is a *runtime.APIError,
// as with Chat.
func (c *Client) ChatStream(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*runtime.Stream[Chunk], error) {
	req, err := c.ChatRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "text/event-stream", c.timeout)
	if err != nil {
		return nil, err
	}
	return runtime.OpenStream[Chunk](res, body, []runtime.Target{
		{Status: "400", MediaType: "application/problem+json", Dst: new(Problem)},
	})
}

// ChatStreamWithResponse is ChatWithResponse over a live stream: it asks for
// text/event-stream, and a 2xx response in a sequential media type comes back with Stream200
// set, Body nil and HTTPResponse.Body open until the stream is closed. Any other response is read
// and decoded as ChatWithResponse reads it. An error is returned with the response.
func (c *Client) ChatStreamWithResponse(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*ChatResponse, error) {
	req, err := c.ChatRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "text/event-stream", c.timeout)
	if err != nil {
		return nil, err
	}

	out := &ChatResponse{HTTPResponse: res, Body: body}
	out.Stream200, err = runtime.DecodeStream[Chunk](res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out.JSON200},
		{Status: "200", MediaType: "text/event-stream", Dst: &out.EventStream200},
		{Status: "400", MediaType: "application/problem+json", Dst: &out.ProblemJSON400},
		{Status: "200", IsHeaders: true, Dst: &out.Headers200},
	})
	if err != nil {
		return out, err
	}
	return out, nil
}

// ChatRequest builds the request of POST /chat and runs the editors of the client on it, then
// editors.
func (c *Client) ChatRequest(ctx context.Context, opts *ChatRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &ChatRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/chat")
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json")
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, b, editors)
}

// ListEvents calls GET /events.
//
// # Follow the events
//
// A response outside 2xx comes back as a *runtime.APIError, wrapping the error type of its status
// when the spec documents one.
func (c *Client) ListEvents(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) error {
	req, err := c.ListEventsRequest(ctx, opts, editors...)
	if err != nil {
		return err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return err
	}
	return runtime.DecodeSuccess(res, body, nil)
}

// ListEventsWithResponse is ListEvents with the whole response: its status, its headers, its raw
// body, and the body decoded into the field of its status and media type. A status outside 2xx is
// no error here. A body or header that does not decode is an error, returned with the response.
func (c *Client) ListEventsWithResponse(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*ListEventsResponse, error) {
	req, err := c.ListEventsRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	out := &ListEventsResponse{HTTPResponse: res, Body: body}
	return out, nil
}

// ListEventsStream is ListEvents over a live stream: it asks for text/event-stream and returns the
// frames of a 2xx response in a sequential media type as they arrive. The caller closes the stream.
// Any other 2xx response is runtime.ErrContentType; a response outside 2xx is a *runtime.APIError,
// as with ListEvents.
func (c *Client) ListEventsStream(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*runtime.Stream[ListEventsResponseItem], error) {
	req, err := c.ListEventsRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "text/event-stream", c.timeout)
	if err != nil {
		return nil, err
	}
	return runtime.OpenStream[ListEventsResponseItem](res, body, nil)
}

// ListEventsStreamWithResponse is ListEventsWithResponse over a live stream: it asks for
// text/event-stream, and a 2xx response in a sequential media type comes back with Stream200
// set, Body nil and HTTPResponse.Body open until the stream is closed. Any other response is read
// and decoded as ListEventsWithResponse reads it. An error is returned with the response.
func (c *Client) ListEventsStreamWithResponse(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*ListEventsResponse, error) {
	req, err := c.ListEventsRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "text/event-stream", c.timeout)
	if err != nil {
		return nil, err
	}

	out := &ListEventsResponse{HTTPResponse: res, Body: body}
	if runtime.IsStreaming(res) {
		out.Stream200 = runtime.NewStream[ListEventsResponseItem](res)
	}
	return out, nil
}

// ListEventsRequest builds the request of GET /events and runs the editors of the client on it, then
// editors.
func (c *Client) ListEventsRequest(ctx context.Context, opts *ListEventsRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &ListEventsRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/events")
	return c.newRequest(ctx, b, editors)
}

// TailLog calls GET /logs/{job}.
//
// # Follow the log of a job
//
// It returns the body of a 200 response. A response outside 2xx, or a 2xx the spec does
// not list, comes back as a *runtime.APIError, wrapping the error type of its status when the spec
// documents one.
func (c *Client) TailLog(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponseItem, error) {
	req, err := c.TailLogRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out *TailLogResponseItem
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/x-ndjson", Dst: &out},
		{Status: "404", MediaType: "application/problem+json", Dst: new(Problem)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// TailLogWithResponse is TailLog with the whole response: its status, its headers, its raw
// body, and the body decoded into the field of its status and media type. A status outside 2xx is
// no error here. A body or header that does not decode is an error, returned with the response.
func (c *Client) TailLogWithResponse(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponse, error) {
	req, err := c.TailLogRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	out := &TailLogResponse{HTTPResponse: res, Body: body}
	if err = runtime.Decode(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/x-ndjson", Dst: &out.Ndjson200},
		{Status: "404", MediaType: "application/problem+json", Dst: &out.ProblemJSON404},
	}); err != nil {
		return out, err
	}
	return out, nil
}

// TailLogStream is TailLog over a live stream: it asks for application/x-ndjson and returns the
// frames of a 2xx response in a sequential media type as they arrive. The caller closes the stream.
// Any other 2xx response is runtime.ErrContentType; a response outside 2xx is a *runtime.APIError,
// as with TailLog.
func (c *Client) TailLogStream(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*runtime.Stream[[]byte], error) {
	req, err := c.TailLogRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "application/x-ndjson", c.timeout)
	if err != nil {
		return nil, err
	}
	return runtime.OpenStream[[]byte](res, body, []runtime.Target{
		{Status: "404", MediaType: "application/problem+json", Dst: new(Problem)},
	})
}

// TailLogStreamWithResponse is TailLogWithResponse over a live stream: it asks for
// application/x-ndjson, and a 2xx response in a sequential media type comes back with Stream200
// set, Body nil and HTTPResponse.Body open until the stream is closed. Any other response is read
// and decoded as TailLogWithResponse reads it. An error is returned with the response.
func (c *Client) TailLogStreamWithResponse(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*TailLogResponse, error) {
	req, err := c.TailLogRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.SendStream(c.doer, req, "application/x-ndjson", c.timeout)
	if err != nil {
		return nil, err
	}

	out := &TailLogResponse{HTTPResponse: res, Body: body}
	out.Stream200, err = runtime.DecodeStream[[]byte](res, body, []runtime.Target{
		{Status: "200", MediaType: "application/x-ndjson", Dst: &out.Ndjson200},
		{Status: "404", MediaType: "application/problem+json", Dst: &out.ProblemJSON404},
	})
	if err != nil {
		return out, err
	}
	return out, nil
}

// TailLogRequest builds the request of GET /logs/{job} and runs the editors of the client on it, then
// editors.
func (c *Client) TailLogRequest(ctx context.Context, opts *TailLogRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &TailLogRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/logs/{job}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.Job, runtime.Param{Name: "job", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, b, editors)
}

// newRequest builds b against the base URL and runs the editors of the client on the request, then
// editors.
func (c *Client) newRequest(ctx context.Context, b *runtime.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
