// Code generated by mockzilla-codegen. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"slices"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Shape struct {
	Name   *string      `json:"name,omitempty"`
	Stamp  []byte       `json:"stamp,omitzero"`
	Vertex *Vertex      `json:"vertex,omitempty"`
	Labels *ShapeLabels `json:"labels,omitempty"`
	Origin *Point       `json:"origin,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (s Shape) Validate() error {
	var errs validation.Errors
	if s.Vertex != nil {
		errs.Append("vertex", s.Vertex.Validate())
	}
	return errs.Err()
}

type ShapeLabels struct {
	Main                 *string           `json:"main,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// Get returns the additional property name and whether it is set.
func (s ShapeLabels) Get(name string) (value string, found bool) {
	value, found = s.AdditionalProperties[name]
	return value, found
}

// Set stores value as the additional property name.
func (s *ShapeLabels) Set(name string, value string) {
	if s.AdditionalProperties == nil {
		s.AdditionalProperties = make(map[string]string)
	}
	s.AdditionalProperties[name] = value
}

// MarshalJSON writes the properties, then the additional properties in key order.
func (s ShapeLabels) MarshalJSON() ([]byte, error) {
	type plain ShapeLabels
	return runtime.MarshalAdditional(plain(s), s.AdditionalProperties, "main")
}

// UnmarshalJSON reads the properties, and every other key into AdditionalProperties.
func (s *ShapeLabels) UnmarshalJSON(data []byte) error {
	type plain ShapeLabels
	return runtime.UnmarshalAdditional(data, (*plain)(s), &s.AdditionalProperties, "main")
}

// UnmarshalForm reads the properties, and every other name of the form into AdditionalProperties.
func (s *ShapeLabels) UnmarshalForm(form *multipart.Form) error {
	type plain ShapeLabels
	return runtime.UnmarshalAdditionalForm(form, (*plain)(s), &s.AdditionalProperties, "main")
}

type Point struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Busy struct {
	Message string `json:"message"`
	Retry   int    `json:"retry"`
}

type Invalid struct {
	Message string `json:"message"`
	Field   string `json:"field"`
}

type Link struct {
	URL string `json:"url"`
}

type Upload struct {
	File     runtime.File `json:"file"`
	Checksum []byte       `json:"checksum,omitzero"`
}

// Vertex is one of String or Point.
type Vertex struct {
	String *string `json:"-"`
	Point  *Point  `json:"-"`
}

// MarshalJSON writes the variant that is set.
func (v Vertex) MarshalJSON() ([]byte, error) {
	var set []any
	if v.String != nil {
		set = append(set, v.String)
	}
	if v.Point != nil {
		set = append(set, v.Point)
	}
	return runtime.MarshalOneOf(nil, set...)
}

// UnmarshalJSON sets the variant data matches.
func (v *Vertex) UnmarshalJSON(data []byte) error {
	*v = Vertex{}
	return runtime.UnmarshalUnion(data, v.union())
}

// UnmarshalForm sets the variant the form matches.
func (v *Vertex) UnmarshalForm(form *multipart.Form) error {
	*v = Vertex{}
	return runtime.UnmarshalUnionForm(form, nil, v.union())
}

func (v *Vertex) union() runtime.Union {
	return runtime.Union{
		Variants: []runtime.Variant{
			{
				Name: "String",
				Kind: runtime.KindString,
				Into: runtime.Into(&v.String),
			},
			{
				Name:     "Point",
				Kind:     runtime.KindObject,
				Required: []string{"x", "y"},
				Known:    []string{"x", "y"},
				Into:     runtime.Into(&v.Point),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (v Vertex) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(v.String != nil, v.Point != nil))
	return errs.Err()
}

// Fault is one of Busy or Invalid.
type Fault struct {
	Busy    *Busy    `json:"-"`
	Invalid *Invalid `json:"-"`
}

// MarshalJSON writes the variant that is set.
func (f Fault) MarshalJSON() ([]byte, error) {
	var set []any
	if f.Busy != nil {
		set = append(set, f.Busy)
	}
	if f.Invalid != nil {
		set = append(set, f.Invalid)
	}
	return runtime.MarshalOneOf(nil, set...)
}

// UnmarshalJSON sets the variant data matches.
func (f *Fault) UnmarshalJSON(data []byte) error {
	*f = Fault{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Variants: []runtime.Variant{
			{
				Name:     "Busy",
				Kind:     runtime.KindObject,
				Required: []string{"message", "retry"},
				Known:    []string{"message", "retry"},
				Into:     runtime.Into(&f.Busy),
			},
			{
				Name:     "Invalid",
				Kind:     runtime.KindObject,
				Required: []string{"message", "field"},
				Known:    []string{"message", "field"},
				Into:     runtime.Into(&f.Invalid),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (f Fault) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(f.Busy != nil, f.Invalid != nil))
	return errs.Err()
}

// Error returns the message at message.
func (f Fault) Error() string {
	return runtime.ErrorMessage(f, "message", "Fault")
}

// Attachment is one of Link or Upload.
type Attachment struct {
	Link   *Link   `json:"-"`
	Upload *Upload `json:"-"`
}

// MarshalJSON writes the variant that is set.
func (a Attachment) MarshalJSON() ([]byte, error) {
	var set []any
	if a.Link != nil {
		set = append(set, a.Link)
	}
	if a.Upload != nil {
		set = append(set, a.Upload)
	}
	return runtime.MarshalOneOf(nil, set...)
}

// UnmarshalJSON sets the variant data matches.
func (a *Attachment) UnmarshalJSON(data []byte) error {
	*a = Attachment{}
	return runtime.UnmarshalUnion(data, a.union())
}

// UnmarshalForm sets the variant the form matches.
func (a *Attachment) UnmarshalForm(form *multipart.Form) error {
	*a = Attachment{}
	return runtime.UnmarshalUnionForm(form, nil, a.union())
}

func (a *Attachment) union() runtime.Union {
	return runtime.Union{
		Variants: []runtime.Variant{
			{
				Name:     "Link",
				Kind:     runtime.KindObject,
				Required: []string{"url"},
				Known:    []string{"url"},
				Into:     runtime.Into(&a.Link),
			},
			{
				Name:     "Upload",
				Kind:     runtime.KindObject,
				Required: []string{"file"},
				Known:    []string{"file", "checksum"},
				Into:     runtime.Into(&a.Upload),
			},
		},
	}
}

// Validate checks the value against the constraints of the spec.
func (a Attachment) Validate() error {
	var errs validation.Errors
	errs.Append("", validation.ExactlyOne(a.Link != nil, a.Upload != nil))
	return errs.Err()
}

type PostAttachmentResponse200 = string

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// PostForm handles POST /form.
	PostForm(ctx context.Context, opts *PostFormServiceRequestOptions) (*PostFormResponseData, error)
	// PostMultipart handles POST /multipart.
	PostMultipart(ctx context.Context, opts *PostMultipartServiceRequestOptions) (*PostMultipartResponseData, error)
	// PostAttachment handles POST /attachments.
	PostAttachment(ctx context.Context, opts *PostAttachmentServiceRequestOptions) (*PostAttachmentResponseData, error)
}

// PostFormServiceRequestOptions is what PostForm receives.
type PostFormServiceRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	Body       *Shape
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostFormServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PostFormResponseData is what PostForm returns.
type PostFormResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostFormResponseData200 returns the 200 response with its application/json body.
func NewPostFormResponseData200(body *Shape) *PostFormResponseData {
	return &PostFormResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewPostFormResponseDataDefault returns the default response with its application/json body.
func NewPostFormResponseDataDefault(status int, body *Fault) *PostFormResponseData {
	return &PostFormResponseData{Status: status, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostFormResponseData) WithStatus(code int) *PostFormResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostFormResponseData) WithHeaders(h http.Header) *PostFormResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostFormResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostFormResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostFormResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostFormResponseData) ContentType() string {
	return r.contentType
}

// PostMultipartServiceRequestOptions is what PostMultipart receives.
type PostMultipartServiceRequestOptions struct {
	// Body sent as multipart/form-data.
	Body       *Shape
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostMultipartServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PostMultipartResponseData is what PostMultipart returns.
type PostMultipartResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostMultipartResponseData returns the 200 response with its application/json body.
func NewPostMultipartResponseData(body *Shape) *PostMultipartResponseData {
	return &PostMultipartResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostMultipartResponseData) WithStatus(code int) *PostMultipartResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostMultipartResponseData) WithHeaders(h http.Header) *PostMultipartResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostMultipartResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostMultipartResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostMultipartResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostMultipartResponseData) ContentType() string {
	return r.contentType
}

// PostAttachmentServiceRequestOptions is what PostAttachment receives.
type PostAttachmentServiceRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *Attachment
	// Body sent as multipart/form-data.
	BodyMultipart *Attachment
	RawRequest    *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostAttachmentServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.BodyForm != nil {
		errs.Append("body", o.BodyForm.Validate())
	}
	if o.BodyMultipart != nil {
		errs.Append("body", o.BodyMultipart.Validate())
	}
	return errs.Err()
}

// PostAttachmentResponseData is what PostAttachment returns.
type PostAttachmentResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostAttachmentResponseData returns the 200 response with its text/plain body.
func NewPostAttachmentResponseData(body *PostAttachmentResponse200) *PostAttachmentResponseData {
	return &PostAttachmentResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *PostAttachmentResponseData) WithStatus(code int) *PostAttachmentResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostAttachmentResponseData) WithHeaders(h http.Header) *PostAttachmentResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostAttachmentResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostAttachmentResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostAttachmentResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostAttachmentResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// PostForm handles POST /form.
func (a *HTTPAdapter) PostForm(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostForm"))
	opts := &PostFormServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.Body, true, nil); err != nil {
			a.failDecode(w, r, "PostForm", err)
			return
		}
	case "":
		a.failDecode(w, r, "PostForm", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostForm", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostForm(r.Context(), opts)
	if err != nil {
		if e, ok := runtime.AsError[Fault](err); ok {
			w.Header().Set("Content-Type", "application/json")
			a.opts.ErrorHandler.HandleError(w, r, 500, e)
			return
		}
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostForm", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostForm", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostForm", res)
}

// PostMultipart handles POST /multipart.
func (a *HTTPAdapter) PostMultipart(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostMultipart"))
	opts := &PostMultipartServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "multipart/form-data":
		opts.Body = &Shape{}
		if err := runtime.DecodeMultipart(r, opts.Body, a.opts.MultipartMaxMemory, nil); err != nil {
			a.failDecode(w, r, "PostMultipart", err)
			return
		}
	case "":
		a.failDecode(w, r, "PostMultipart", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostMultipart", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostMultipart(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostMultipart", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostMultipart", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostMultipart", res)
}

// PostAttachment handles POST /attachments.
func (a *HTTPAdapter) PostAttachment(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostAttachment"))
	opts := &PostAttachmentServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.BodyForm, true, nil); err != nil {
			a.failDecode(w, r, "PostAttachment", err)
			return
		}
	case "multipart/form-data":
		opts.BodyMultipart = &Attachment{}
		if err := runtime.DecodeMultipart(r, opts.BodyMultipart, a.opts.MultipartMaxMemory, nil); err != nil {
			a.failDecode(w, r, "PostAttachment", err)
			return
		}
	case "":
		a.failDecode(w, r, "PostAttachment", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PostAttachment", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostAttachment(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostAttachment", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PostAttachment", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PostAttachment", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/form", a.PostForm)
		r.Post("/multipart", a.PostMultipart)
		r.Post("/attachments", a.PostAttachment)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}

// PostFormRequestOptions is what PostForm sends.
type PostFormRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	Body *Shape
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostFormRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PostMultipartRequestOptions is what PostMultipart sends.
type PostMultipartRequestOptions struct {
	// Body sent as multipart/form-data.
	Body *Shape
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostMultipartRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PostAttachmentRequestOptions is what PostAttachment sends.
type PostAttachmentRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	BodyForm *Attachment
	// Body sent as multipart/form-data.
	BodyMultipart *Attachment
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostAttachmentRequestOptions) Validate() error {
	var errs validation.Errors
	if o.BodyForm != nil {
		errs.Append("body", o.BodyForm.Validate())
	}
	if o.BodyMultipart != nil {
		errs.Append("body", o.BodyMultipart.Validate())
	}
	return errs.Err()
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// PostForm calls POST /form.
	PostForm(ctx context.Context, opts *PostFormRequestOptions, editors ...RequestEditor) (*Shape, error)
	// PostMultipart calls POST /multipart.
	PostMultipart(ctx context.Context, opts *PostMultipartRequestOptions, editors ...RequestEditor) (*Shape, error)
	// PostAttachment calls POST /attachments.
	PostAttachment(ctx context.Context, opts *PostAttachmentRequestOptions, editors ...RequestEditor) (*PostAttachmentResponse200, error)
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *runtime.APIError.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// PostForm calls POST /form.
func (c *Client) PostForm(ctx context.Context, opts *PostFormRequestOptions, editors ...RequestEditor) (*Shape, error) {
	req, err := c.PostFormRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Shape
	if err = runtime.DecodeSuccess(res, body, []runtime.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
		{Status: "default", MediaType: "application/json", Dst: new(Fault)},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// PostFormRequest builds the request of POST /form.
func (c *Client) PostFormRequest(ctx context.Context, opts *PostFormRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &PostFormRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/form")
	switch {
	case opts.Body != nil:
		b.FormBody(opts.Body, nil)
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "PostForm", b, editors)
}

// PostMultipart calls POST /multipart.
func (c *Client) PostMultipart(ctx context.Context, opts *PostMultipartRequestOptions, editors ...RequestEditor) (*Shape, error) {
	req, err := c.PostMultipartRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Shape
	if err = runtime.DecodeSuccess(res, body, []runtime.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// PostMultipartRequest builds the request of POST /multipart.
func (c *Client) PostMultipartRequest(ctx context.Context, opts *PostMultipartRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &PostMultipartRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/multipart")
	switch {
	case opts.Body != nil:
		b.MultipartBody(opts.Body, nil)
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "PostMultipart", b, editors)
}

// PostAttachment calls POST /attachments.
func (c *Client) PostAttachment(ctx context.Context, opts *PostAttachmentRequestOptions, editors ...RequestEditor) (*PostAttachmentResponse200, error) {
	req, err := c.PostAttachmentRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, "text/plain", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *PostAttachmentResponse200
	if err = runtime.DecodeSuccess(res, body, []runtime.ResponseTarget{
		{Status: "200", MediaType: "text/plain", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// PostAttachmentRequest builds the request of POST /attachments.
func (c *Client) PostAttachmentRequest(ctx context.Context, opts *PostAttachmentRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &PostAttachmentRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/attachments")
	switch {
	case opts.BodyForm != nil:
		b.FormBody(opts.BodyForm, nil)
	case opts.BodyMultipart != nil:
		b.MultipartBody(opts.BodyMultipart, nil)
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "PostAttachment", b, editors)
}

func (c *Client) newRequest(ctx context.Context, id string, b *runtime.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	ctx = runtime.WithOperationID(ctx, id)
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
