// Code generated by mockzilla-codegen. DO NOT EDIT.

package bodies

import (
	"context"
	"errors"
	"io"
	"iter"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Note struct {
	Text  string `json:"text"`
	Stars *int   `json:"stars,omitempty"`
}

type UploadRequestBody struct {
	Title *string       `json:"title,omitempty"`
	File  *runtime.File `json:"file,omitempty"`
	Tags  []string      `json:"tags,omitzero"`
	Meta  *Note         `json:"meta,omitempty"`
}

type PostTextRequestBody = string

type PutFileRequestBody = runtime.File

type PostAnyXMLRequestBody = string

type PostAnyXMLRequestBody2 = string

type GetQuoteResponse200 = string

type GetCountResponse200 = int

type UploadResponse200 map[string]any

type PostTextResponse200 = string

type PutFileResponse200 = runtime.File

type PostAnyResponse200 = string

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// PostJSON handles POST /json.
	PostJSON(ctx context.Context, opts *PostJSONServiceRequestOptions) (*PostJSONResponseData, error)
	// GetForm handles GET /form.
	GetForm(ctx context.Context, opts *GetFormServiceRequestOptions) (*GetFormResponseData, error)
	// PostForm handles POST /form.
	PostForm(ctx context.Context, opts *PostFormServiceRequestOptions) (*PostFormResponseData, error)
	// GetQuote handles GET /quote.
	GetQuote(ctx context.Context, opts *GetQuoteServiceRequestOptions) (*GetQuoteResponseData, error)
	// GetCount handles GET /count.
	GetCount(ctx context.Context, opts *GetCountServiceRequestOptions) (*GetCountResponseData, error)
	// ListNotes handles GET /notes.
	ListNotes(ctx context.Context, opts *ListNotesServiceRequestOptions) (*ListNotesResponseData, error)
	// Upload handles POST /upload.
	Upload(ctx context.Context, opts *UploadServiceRequestOptions) (*UploadResponseData, error)
	// PostText handles POST /text.
	PostText(ctx context.Context, opts *PostTextServiceRequestOptions) (*PostTextResponseData, error)
	// PutFile handles PUT /file.
	PutFile(ctx context.Context, opts *PutFileServiceRequestOptions) (*PutFileResponseData, error)
	// PostAny handles POST /any.
	PostAny(ctx context.Context, opts *PostAnyServiceRequestOptions) (*PostAnyResponseData, error)
}

// PostJSONServiceRequestOptions is what PostJSON receives.
type PostJSONServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *Note
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostJSONServiceRequestOptions) Validate() error {
	return nil
}

// PostJSONResponseData is what PostJSON returns.
type PostJSONResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostJSONResponseData returns the 200 response with its application/json body.
func NewPostJSONResponseData(body *Note) *PostJSONResponseData {
	return &PostJSONResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostJSONResponseData) WithStatus(code int) *PostJSONResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostJSONResponseData) WithHeaders(h http.Header) *PostJSONResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostJSONResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostJSONResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostJSONResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostJSONResponseData) ContentType() string {
	return r.contentType
}

// GetFormServiceRequestOptions is what GetForm receives.
type GetFormServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetFormServiceRequestOptions) Validate() error {
	return nil
}

// GetFormResponseData is what GetForm returns.
type GetFormResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetFormResponseData returns the 200 response with its application/x-www-form-urlencoded body.
func NewGetFormResponseData(body *Note) *GetFormResponseData {
	return &GetFormResponseData{Status: 200, Body: body, contentType: "application/x-www-form-urlencoded"}
}

// WithStatus sets the status code.
func (r *GetFormResponseData) WithStatus(code int) *GetFormResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetFormResponseData) WithHeaders(h http.Header) *GetFormResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetFormResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetFormResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetFormResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetFormResponseData) ContentType() string {
	return r.contentType
}

// PostFormServiceRequestOptions is what PostForm receives.
type PostFormServiceRequestOptions struct {
	// Body sent as application/x-www-form-urlencoded.
	Body       *Note
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostFormServiceRequestOptions) Validate() error {
	return nil
}

// PostFormResponseData is what PostForm returns.
type PostFormResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostFormResponseData returns the 200 response with its application/json body.
func NewPostFormResponseData(body *Note) *PostFormResponseData {
	return &PostFormResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PostFormResponseData) WithStatus(code int) *PostFormResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostFormResponseData) WithHeaders(h http.Header) *PostFormResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostFormResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostFormResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostFormResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostFormResponseData) ContentType() string {
	return r.contentType
}

// GetQuoteServiceRequestOptions is what GetQuote receives.
type GetQuoteServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetQuoteServiceRequestOptions) Validate() error {
	return nil
}

// GetQuoteResponseData is what GetQuote returns.
type GetQuoteResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetQuoteResponseData returns the 200 response with its application/json body.
func NewGetQuoteResponseData(body *GetQuoteResponse200) *GetQuoteResponseData {
	return &GetQuoteResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *GetQuoteResponseData) WithStatus(code int) *GetQuoteResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetQuoteResponseData) WithHeaders(h http.Header) *GetQuoteResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetQuoteResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetQuoteResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetQuoteResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetQuoteResponseData) ContentType() string {
	return r.contentType
}

// GetCountServiceRequestOptions is what GetCount receives.
type GetCountServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetCountServiceRequestOptions) Validate() error {
	return nil
}

// GetCountResponseData is what GetCount returns.
type GetCountResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetCountResponseData returns the 200 response with its text/plain body.
func NewGetCountResponseData(body *GetCountResponse200) *GetCountResponseData {
	return &GetCountResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *GetCountResponseData) WithStatus(code int) *GetCountResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetCountResponseData) WithHeaders(h http.Header) *GetCountResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetCountResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetCountResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetCountResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetCountResponseData) ContentType() string {
	return r.contentType
}

// ListNotesServiceRequestOptions is what ListNotes receives.
type ListNotesServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListNotesServiceRequestOptions) Validate() error {
	return nil
}

// ListNotesResponseData is what ListNotes returns.
type ListNotesResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewListNotesResponseData returns the 200 response that streams frames as text/event-stream.
func NewListNotesResponseData(frames iter.Seq[Note]) *ListNotesResponseData {
	return &ListNotesResponseData{Status: 200, Body: frames, contentType: "text/event-stream"}
}

// WithStatus sets the status code.
func (r *ListNotesResponseData) WithStatus(code int) *ListNotesResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ListNotesResponseData) WithHeaders(h http.Header) *ListNotesResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ListNotesResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ListNotesResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ListNotesResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *ListNotesResponseData) ContentType() string {
	return r.contentType
}

// UploadServiceRequestOptions is what Upload receives.
type UploadServiceRequestOptions struct {
	// Body sent as multipart/form-data.
	Body       *UploadRequestBody
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UploadServiceRequestOptions) Validate() error {
	return nil
}

// UploadResponseData is what Upload returns.
type UploadResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUploadResponseData returns the 200 response with its application/json body.
func NewUploadResponseData(body UploadResponse200) *UploadResponseData {
	return &UploadResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *UploadResponseData) WithStatus(code int) *UploadResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UploadResponseData) WithHeaders(h http.Header) *UploadResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UploadResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UploadResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UploadResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UploadResponseData) ContentType() string {
	return r.contentType
}

// PostTextServiceRequestOptions is what PostText receives.
type PostTextServiceRequestOptions struct {
	// Body sent as text/plain.
	BodyText *PostTextRequestBody
	// Body sent as application/octet-stream.
	BodyOctetStream []byte
	RawRequest      *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostTextServiceRequestOptions) Validate() error {
	return nil
}

// PostTextResponseData is what PostText returns.
type PostTextResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostTextResponseData returns the 200 response with its text/plain body.
func NewPostTextResponseData(body *PostTextResponse200) *PostTextResponseData {
	return &PostTextResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *PostTextResponseData) WithStatus(code int) *PostTextResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostTextResponseData) WithHeaders(h http.Header) *PostTextResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostTextResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostTextResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostTextResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostTextResponseData) ContentType() string {
	return r.contentType
}

// PutFileServiceRequestOptions is what PutFile receives.
type PutFileServiceRequestOptions struct {
	// Body sent as image/png.
	Body       *PutFileRequestBody
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PutFileServiceRequestOptions) Validate() error {
	return nil
}

// PutFileResponseData is what PutFile returns.
type PutFileResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPutFileResponseData returns the 200 response with its image/png body.
func NewPutFileResponseData(body *PutFileResponse200) *PutFileResponseData {
	return &PutFileResponseData{Status: 200, Body: body, contentType: "image/png"}
}

// WithStatus sets the status code.
func (r *PutFileResponseData) WithStatus(code int) *PutFileResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PutFileResponseData) WithHeaders(h http.Header) *PutFileResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PutFileResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PutFileResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PutFileResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PutFileResponseData) ContentType() string {
	return r.contentType
}

// PostAnyServiceRequestOptions is what PostAny receives.
type PostAnyServiceRequestOptions struct {
	// Body sent as application/xml.
	BodyXML *PostAnyXMLRequestBody
	// Body sent as text/xml.
	BodyTextXML *PostAnyXMLRequestBody2
	// Body sent as */*.
	BodyAny    []byte
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PostAnyServiceRequestOptions) Validate() error {
	return nil
}

// PostAnyResponseData is what PostAny returns.
type PostAnyResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPostAnyResponseData returns the 200 response with its text/plain body.
func NewPostAnyResponseData(body *PostAnyResponse200) *PostAnyResponseData {
	return &PostAnyResponseData{Status: 200, Body: body, contentType: "text/plain"}
}

// WithStatus sets the status code.
func (r *PostAnyResponseData) WithStatus(code int) *PostAnyResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PostAnyResponseData) WithHeaders(h http.Header) *PostAnyResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PostAnyResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PostAnyResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PostAnyResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *PostAnyResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       httpserver.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 1048576,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// PostJSON handles POST /json.
func (a *HTTPAdapter) PostJSON(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostJSON"))
	opts := &PostJSONServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, false); err != nil {
			a.failDecode(w, r, "PostJSON", err)
			return
		}
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PostJSON", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostJSON(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostJSON", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostJSON", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostJSON", res)
}

// GetForm handles GET /form.
func (a *HTTPAdapter) GetForm(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetForm"))
	opts := &GetFormServiceRequestOptions{RawRequest: r}

	res, err := a.svc.GetForm(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetForm", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetForm", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetForm", res)
}

// PostForm handles POST /form.
func (a *HTTPAdapter) PostForm(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostForm"))
	opts := &PostFormServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/x-www-form-urlencoded":
		if err := runtime.DecodeForm(r.Body, &opts.Body, true, nil); err != nil {
			a.failDecode(w, r, "PostForm", err)
			return
		}
	case "":
		a.failDecode(w, r, "PostForm", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PostForm", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostForm(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostForm", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostForm", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostForm", res)
}

// GetQuote handles GET /quote.
func (a *HTTPAdapter) GetQuote(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetQuote"))
	opts := &GetQuoteServiceRequestOptions{RawRequest: r}

	res, err := a.svc.GetQuote(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetQuote", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetQuote", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetQuote", res)
}

// GetCount handles GET /count.
func (a *HTTPAdapter) GetCount(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "GetCount"))
	opts := &GetCountServiceRequestOptions{RawRequest: r}

	res, err := a.svc.GetCount(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetCount", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetCount", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetCount", res)
}

// ListNotes handles GET /notes.
func (a *HTTPAdapter) ListNotes(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "ListNotes"))
	opts := &ListNotesServiceRequestOptions{RawRequest: r}

	res, err := a.svc.ListNotes(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListNotes", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListNotes", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "ListNotes", res)
}

// Upload handles POST /upload.
func (a *HTTPAdapter) Upload(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "Upload"))
	opts := &UploadServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "multipart/form-data":
		opts.Body = &UploadRequestBody{}
		if err := runtime.DecodeMultipart(r, opts.Body, a.opts.MultipartMaxMemory, nil); err != nil {
			a.failDecode(w, r, "Upload", err)
			return
		}
	case "":
		a.failDecode(w, r, "Upload", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "Upload", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.Upload(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "Upload", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "Upload", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "Upload", res)
}

// PostText handles POST /text.
func (a *HTTPAdapter) PostText(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostText"))
	opts := &PostTextServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "text/plain":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostText", err)
			return
		}
		opts.BodyText = runtime.Ptr(PostTextRequestBody(text))
	case "application/octet-stream":
		data, err := runtime.DecodeBytes(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostText", err)
			return
		}
		opts.BodyOctetStream = data
	case "":
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PostText", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PostText(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostText", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostText", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostText", res)
}

// PutFile handles PUT /file.
func (a *HTTPAdapter) PutFile(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PutFile"))
	opts := &PutFileServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "image/png":
		file, err := runtime.DecodeFile(r, true)
		if err != nil {
			a.failDecode(w, r, "PutFile", err)
			return
		}
		opts.Body = runtime.Ptr(PutFileRequestBody(file))
	case "":
		a.failDecode(w, r, "PutFile", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "PutFile", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.PutFile(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PutFile", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PutFile", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PutFile", res)
}

// PostAny handles POST /any.
func (a *HTTPAdapter) PostAny(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "PostAny"))
	opts := &PostAnyServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/xml":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyXML = runtime.Ptr(PostAnyXMLRequestBody(text))
	case "text/xml":
		text, err := runtime.DecodeText(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyTextXML = runtime.Ptr(PostAnyXMLRequestBody2(text))
	case "":
	default:
		data, err := runtime.DecodeBytes(r.Body, false)
		if err != nil {
			a.failDecode(w, r, "PostAny", err)
			return
		}
		opts.BodyAny = data
	}

	res, err := a.svc.PostAny(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostAny", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "PostAny", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "PostAny", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/json", a.PostJSON)
		r.Get("/form", a.GetForm)
		r.Post("/form", a.PostForm)
		r.Get("/quote", a.GetQuote)
		r.Get("/count", a.GetCount)
		r.Get("/notes", a.ListNotes)
		r.Post("/upload", a.Upload)
		r.Post("/text", a.PostText)
		r.Put("/file", a.PutFile)
		r.Post("/any", a.PostAny)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}
