// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/examples/server/chi/split/models"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

// BooksInterface is what the generated handlers call. Implement it with the business logic.
type BooksInterface interface {
	// GetBook handles GET /books/{isbn}.
	GetBook(ctx context.Context, opts *GetBookServiceRequestOptions) (*GetBookResponseData, error)
}

// GetBookServiceRequestOptions is what GetBook receives.
type GetBookServiceRequestOptions struct {
	PathParams *models.GetBookPathParams
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetBookServiceRequestOptions) Validate() error {
	return nil
}

// GetBookResponseData is what GetBook returns.
type GetBookResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetBookResponseData200 returns the 200 response with its application/json body.
func NewGetBookResponseData200(body *models.Book) *GetBookResponseData {
	return &GetBookResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetBookResponseData404 returns the 404 response with its application/json body.
func NewGetBookResponseData404(body *models.Problem) *GetBookResponseData {
	return &GetBookResponseData{Status: 404, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *GetBookResponseData) WithStatus(code int) *GetBookResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetBookResponseData) WithHeaders(h http.Header) *GetBookResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetBookResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetBookResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetBookResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *GetBookResponseData) ContentType() string {
	return r.contentType
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        BooksInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc BooksInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// GetBook handles GET /books/{isbn}.
func (a *HTTPAdapter) GetBook(w http.ResponseWriter, r *http.Request) {
	a.operations.Serve(w, r, "GetBook", a.serveGetBook)
}

func (a *HTTPAdapter) serveGetBook(w http.ResponseWriter, r *http.Request) {
	opts := &GetBookServiceRequestOptions{RawRequest: r}
	opts.PathParams = &models.GetBookPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "isbn")), runtime.Param{Name: "isbn", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.Isbn); err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorParse, OperationID: "GetBook", ParamName: "isbn", ParamLocation: "path", Err: err})
		return
	}

	res, err := a.svc.GetBook(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetBook", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "GetBook", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "GetBook", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}
