// Code generated by mockzilla-codegen. DO NOT EDIT.

package nodescriptions

import (
	"context"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpclient"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Pet struct {
	Name string `json:"name"`
}

type GetPetPathParams struct {
	ID string `json:"id"`
}

type DeletePetPathParams struct {
	ID string `json:"id"`
}

// GetPetRequestOptions is what GetPet sends.
type GetPetRequestOptions struct {
	PathParams *GetPetPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetRequestOptions) Validate() error {
	return nil
}

// DeletePetRequestOptions is what DeletePet sends.
type DeletePetRequestOptions struct {
	PathParams *DeletePetPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *DeletePetRequestOptions) Validate() error {
	return nil
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = httpclient.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// GetPet calls GET /pets/{id}.
	GetPet(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*Pet, error)
	// DeletePet calls DELETE /pets/{id}.
	//
	// Deprecated: the spec marks it deprecated.
	DeletePet(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) error
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *httpclient.APIError.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := httpclient.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// GetPet calls GET /pets/{id}.
func (c *Client) GetPet(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*Pet, error) {
	req, err := c.GetPetRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := httpclient.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Pet
	if err = httpclient.DecodeSuccess(res, body, []httpclient.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// GetPetRequest builds the request of GET /pets/{id}.
func (c *Client) GetPetRequest(ctx context.Context, opts *GetPetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &GetPetRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodGet, "/pets/{id}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.ID, runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, "GetPet", b, editors)
}

// DeletePet calls DELETE /pets/{id}.
//
// Deprecated: the spec marks it deprecated.
func (c *Client) DeletePet(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) error {
	req, err := c.DeletePetRequest(ctx, opts, editors...)
	if err != nil {
		return err
	}
	res, body, err := httpclient.Send(c.doer, req, "", c.timeout)
	if err != nil {
		return err
	}
	return httpclient.DecodeSuccess(res, body, nil)
}

// DeletePetRequest builds the request of DELETE /pets/{id}.
func (c *Client) DeletePetRequest(ctx context.Context, opts *DeletePetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &DeletePetRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodDelete, "/pets/{id}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.ID, runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, "DeletePet", b, editors)
}

func (c *Client) newRequest(ctx context.Context, id string, b *httpclient.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	ctx = runtime.WithOperationID(ctx, id)
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
