// Code generated by mockzilla-codegen. DO NOT EDIT.

package streaming

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/url"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Fails to compile when the runtime package does not match the codegen version that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Prompt struct {
	Text   string `json:"text"`
	Stream *bool  `json:"stream,omitempty"`
}

type Reply struct {
	Text string `json:"text"`
}

type Chunk struct {
	Delta *string `json:"delta,omitempty"`
}

type Event struct {
	Seq int `json:"seq"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// Ask the assistant
	//
	// Answers whole as JSON, or as a stream of chunks when the prompt asks for one.
	Chat(ctx context.Context, opts *ChatServiceRequestOptions) (*ChatResponseData, error)
	// Follow the events
	ListEvents(ctx context.Context, opts *ListEventsServiceRequestOptions) (*ListEventsResponseData, error)
}

// ChatServiceRequestOptions is what Chat receives. RawRequest is the request as it came in.
type ChatServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *Prompt
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ChatServiceRequestOptions) Validate() error {
	return nil
}

// ChatResponseData is what Chat returns: the status, the headers and the body of the response.
type ChatResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewChatResponseData returns the response data of status 200 with body as application/json.
func NewChatResponseData(body *Reply) *ChatResponseData {
	return &ChatResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *ChatResponseData) WithStatus(code int) *ChatResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ChatResponseData) WithHeaders(h http.Header) *ChatResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ChatResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ChatResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ChatResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *ChatResponseData) ContentType() string {
	return r.contentType
}

// ListEventsServiceRequestOptions is what ListEvents receives. RawRequest is the request as it came in.
type ListEventsServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListEventsServiceRequestOptions) Validate() error {
	return nil
}

// ListEventsResponseData is what ListEvents returns: the status, the headers and the body of the response.
type ListEventsResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewListEventsResponseData returns the response data of status 200 with body as text/event-stream.
func NewListEventsResponseData(body string) *ListEventsResponseData {
	return &ListEventsResponseData{Status: 200, Body: body, contentType: "text/event-stream"}
}

// WithStatus sets the status code.
func (r *ListEventsResponseData) WithStatus(code int) *ListEventsResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ListEventsResponseData) WithHeaders(h http.Header) *ListEventsResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ListEventsResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ListEventsResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ListEventsResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *ListEventsResponseData) ContentType() string {
	return r.contentType
} // The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
) // ServerOptions is what the adapter and the router are set up with. Router is the router the
// routes go on when one is given; Middleware wraps the routes, outermost first; ErrorHandler
// writes the response of a failed request; JSONDecoder reads JSON bodies.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first, after any middleware added before.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory before parts spill to
// disk.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service: one handler per operation.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

// responseData is what every response data type gives the adapter.
type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// Chat handles POST /chat.
func (a *HTTPAdapter) Chat(w http.ResponseWriter, r *http.Request) {
	opts := &ChatServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "Chat", err)
			return
		}
	case "":
		a.failDecode(w, r, "Chat", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "Chat", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.Chat(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Chat", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Chat", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "Chat", res)
}

// ListEvents handles GET /events.
func (a *HTTPAdapter) ListEvents(w http.ResponseWriter, r *http.Request) {
	opts := &ListEventsServiceRequestOptions{RawRequest: r}

	res, err := a.svc.ListEvents(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "ListEvents", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "ListEvents", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "ListEvents", res)
}

// fail answers a request the handler could not serve.
func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

// failDecode answers a request whose body could not be read.
func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

// write writes the response of the service.
func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	if err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
} // WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router. On a new router the middleware
// WithMiddleware adds wraps everything, unknown paths too; on the router WithRouter gives it
// wraps the generated routes and nothing else.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/chat", adapter.Chat)
		r.Get("/events", adapter.ListEvents)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
} // HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent, to add credentials for one.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// Client calls the API at a base URL, with one method per operation.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL. It sends with an http.Client that gives up
// after 3 * time.Second, unless WithHTTPClient sets another.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{Timeout: 3 * time.Second}}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// WithHTTPClient sends the requests with d, such as an http.Client set up for the API.
func WithHTTPClient(d HTTPDoer) ClientOption {
	return func(c *Client) {
		c.doer = d
	}
}

// WithRequestEditor runs fns on every request before it is sent, after any editor added before.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// newRequest builds b against the base URL and runs the editors on the request.
func (c *Client) newRequest(ctx context.Context, b *runtime.RequestBuilder) (*http.Request, error) {
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range c.editors {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// ChatRequestOptions is what Chat sends: its parameters by location, and its body.
type ChatRequestOptions struct {
	// Body sent as application/json.
	Body *Prompt
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ChatRequestOptions) Validate() error {
	return nil
}

// ListEventsRequestOptions is what ListEvents sends: its parameters by location, and its body.
type ListEventsRequestOptions struct {
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListEventsRequestOptions) Validate() error {
	return nil
} // ClientInterface is what Client implements: one method per operation, so a test double can
// stand in for the client.
type ClientInterface interface {
	// Ask the assistant
	//
	// Answers whole as JSON, or as a stream of chunks when the prompt asks for one.
	Chat(ctx context.Context, opts *ChatRequestOptions) (*Reply, error)
	ChatStream(ctx context.Context, opts *ChatRequestOptions) (*runtime.Stream[Chunk], error)
	// Follow the events
	ListEvents(ctx context.Context, opts *ListEventsRequestOptions) (string, error)
	ListEventsStream(ctx context.Context, opts *ListEventsRequestOptions) (*runtime.Stream[Event], error)
}

var _ ClientInterface = (*Client)(nil)

// ChatRequest builds the request of Chat, with the editors of the client applied.
func (c *Client) ChatRequest(ctx context.Context, opts *ChatRequestOptions) (*http.Request, error) {
	if opts == nil {
		opts = &ChatRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/chat")
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json")
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, b)
}

// Ask the assistant
//
// Answers whole as JSON, or as a stream of chunks when the prompt asks for one.
//
// Chat returns the body of a 200 response. A response outside 2xx comes
// back as a *runtime.APIError, wrapping the error type of its status when the spec documents one.
func (c *Client) Chat(ctx context.Context, opts *ChatRequestOptions) (*Reply, error) {
	req, err := c.ChatRequest(ctx, opts)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req)
	if err != nil {
		return nil, err
	}

	var out *Reply
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// ChatStream is Chat over a live stream: it asks for text/event-stream and returns the
// frames of a 2xx response in a sequential media type as they arrive. The caller closes the stream.
// Any other 2xx response is runtime.ErrContentType; a response outside 2xx is a *runtime.APIError,
// as with Chat.
func (c *Client) ChatStream(ctx context.Context, opts *ChatRequestOptions) (*runtime.Stream[Chunk], error) {
	req, err := c.ChatRequest(ctx, opts)
	if err != nil {
		return nil, err
	}
	return runtime.OpenStream[Chunk](c.doer, req, "text/event-stream", nil)
}

// ListEventsRequest builds the request of ListEvents, with the editors of the client applied.
func (c *Client) ListEventsRequest(ctx context.Context, opts *ListEventsRequestOptions) (*http.Request, error) {
	if opts == nil {
		opts = &ListEventsRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/events")
	return c.newRequest(ctx, b)
}

// Follow the events
//
// ListEvents returns the body of a 200 response. A response outside 2xx comes
// back as a *runtime.APIError, wrapping the error type of its status when the spec documents one.
func (c *Client) ListEvents(ctx context.Context, opts *ListEventsRequestOptions) (string, error) {
	req, err := c.ListEventsRequest(ctx, opts)
	if err != nil {
		return "", err
	}
	res, body, err := runtime.Send(c.doer, req)
	if err != nil {
		return "", err
	}

	var out string
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "text/event-stream", Dst: &out},
	}); err != nil {
		return "", err
	}
	return out, nil
}

// ListEventsStream is ListEvents over a live stream: it asks for text/event-stream and returns the
// frames of a 2xx response in a sequential media type as they arrive. The caller closes the stream.
// Any other 2xx response is runtime.ErrContentType; a response outside 2xx is a *runtime.APIError,
// as with ListEvents.
func (c *Client) ListEventsStream(ctx context.Context, opts *ListEventsRequestOptions) (*runtime.Stream[Event], error) {
	req, err := c.ListEventsRequest(ctx, opts)
	if err != nil {
		return nil, err
	}
	return runtime.OpenStream[Event](c.doer, req, "text/event-stream", nil)
}

// ChatToolInput is the input of the chat tool: the parameters of the operation.
type ChatToolInput struct {
	// The request body, sent as application/json.
	Body *Prompt `json:"body"`
}

// ListEventsToolInput is the input of the list_events tool, which takes nothing.
type ListEventsToolInput struct{}

// MCPTools exposes the operations of the API as MCP tools, each calling the client.
type MCPTools struct {
	client ClientInterface
}

// NewMCPTools returns the tools that call c.
func NewMCPTools(c ClientInterface) *MCPTools {
	return &MCPTools{client: c}
}

// Register adds every tool to s. To add a few, pass the definition and the handler of each to
// mcp.AddTool instead.
func (t *MCPTools) Register(s *mcp.Server) {
	mcp.AddTool(s, t.ChatTool(), t.Chat)
	mcp.AddTool(s, t.ListEventsTool(), t.ListEvents)
}

// ErrMCPStreaming is what a tool answers when its operation streams its response, which a tool
// result cannot carry; read such an operation through the client.
var ErrMCPStreaming = errors.New("the operation answers with a stream, which an MCP tool cannot return")

// ChatTool is the definition of the chat tool: its name, its description and the schema
// of its input.
func (t *MCPTools) ChatTool() *mcp.Tool {
	return &mcp.Tool{
		Name:        "chat",
		Description: "Ask the assistant\n\nAnswers whole as JSON, or as a stream of chunks when the prompt asks for one.",
		InputSchema: json.RawMessage(`{"type":"object","properties":{"body":{"$ref":"#/$defs/Prompt"}},"required":["body"],"additionalProperties":false,"$defs":{"Prompt":{"type":"object","properties":{"text":{"type":"string"},"stream":{"type":"boolean"}},"required":["text"]}}}`),
		Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: false},
	}
}

// Chat handles the chat tool: it calls Chat of the client and answers with what it returns as structured content.
// An error of the client is the error of the tool.
func (t *MCPTools) Chat(ctx context.Context, _ *mcp.CallToolRequest, in ChatToolInput) (*mcp.CallToolResult, any, error) {
	opts := &ChatRequestOptions{
		Body: in.Body,
	}
	out, err := t.client.Chat(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	return nil, out, nil
}

// ListEventsTool is the definition of the list_events tool: its name, its description and the schema
// of its input.
func (t *MCPTools) ListEventsTool() *mcp.Tool {
	return &mcp.Tool{
		Name:        "list_events",
		Description: "Follow the events",
		InputSchema: json.RawMessage(`{"type":"object","additionalProperties":false}`),
		Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true, IdempotentHint: true},
	}
}

// ListEvents handles the list_events tool. ListEvents answers with a stream, so it is ErrMCPStreaming.
func (t *MCPTools) ListEvents(_ context.Context, _ *mcp.CallToolRequest, _ ListEventsToolInput) (*mcp.CallToolResult, any, error) {
	return nil, nil, ErrMCPStreaming
}
