// Code generated by mockzilla-codegen. DO NOT EDIT.

package nullable

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"slices"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Pet struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	// Required, and null when the pet has none.
	Tag      runtime.Nullable[string] `json:"tag"`
	Nickname runtime.Nullable[string] `json:"nickname,omitzero"`
	Age      runtime.Nullable[int]    `json:"age,omitzero"`
	Owner    runtime.Nullable[Owner]  `json:"owner,omitzero"`
	Toys     []string                 `json:"toys,omitzero"`
}

// Validate checks the value against the constraints of the spec.
func (p Pet) Validate() error {
	var errs runtime.ValidationErrors
	if value, ok := p.Nickname.Get(); ok {
		errs.Append("nickname", runtime.MaxLength(value, 20))
	}
	errs.Append("age", runtime.NotNull(p.Age))
	if value, ok := p.Age.Get(); ok {
		errs.Append("age", runtime.Minimum(value, 0, false))
	}
	errs.Append("owner", runtime.NotNull(p.Owner))
	return errs.Err()
}

// Leave a property out to keep it, send null to clear it.
type PetPatch struct {
	Name     runtime.Nullable[string] `json:"name,omitzero"`
	Tag      runtime.Nullable[string] `json:"tag,omitzero"`
	Nickname runtime.Nullable[string] `json:"nickname,omitzero"`
	Age      runtime.Nullable[int]    `json:"age,omitzero"`
	Owner    runtime.Nullable[Owner]  `json:"owner,omitzero"`
	Toys     []string                 `json:"toys,omitzero"`
	Legacy   *string                  `json:"legacy,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (p PetPatch) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("name", runtime.NotNull(p.Name))
	if value, ok := p.Nickname.Get(); ok {
		errs.Append("nickname", runtime.MaxLength(value, 20))
	}
	errs.Append("age", runtime.NotNull(p.Age))
	if value, ok := p.Age.Get(); ok {
		errs.Append("age", runtime.Minimum(value, 0, false))
	}
	return errs.Err()
}

type Owner struct {
	Name string `json:"name"`
}

type UpdatePetPathParams struct {
	ID int `json:"id"`
}

type UpdatePetQuery struct {
	Notify runtime.Nullable[bool] `json:"notify,omitzero"`
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// UpdatePet handles PATCH /pets/{id}.
	UpdatePet(ctx context.Context, opts *UpdatePetServiceRequestOptions) (*UpdatePetResponseData, error)
}

// UpdatePetServiceRequestOptions is what UpdatePet receives.
type UpdatePetServiceRequestOptions struct {
	PathParams *UpdatePetPathParams
	Query      *UpdatePetQuery
	// Body sent as application/json.
	Body       *PetPatch
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UpdatePetServiceRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// UpdatePetResponseData is what UpdatePet returns.
type UpdatePetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewUpdatePetResponseData returns the 200 response with its application/json body.
func NewUpdatePetResponseData(body *Pet) *UpdatePetResponseData {
	return &UpdatePetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *UpdatePetResponseData) WithStatus(code int) *UpdatePetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *UpdatePetResponseData) WithHeaders(h http.Header) *UpdatePetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *UpdatePetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *UpdatePetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *UpdatePetResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *UpdatePetResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

var bodyPresence = runtime.Presence{
	IsChecked: true,
	Objects: []runtime.Object{
		{Name: "Owner", Props: []runtime.Prop{
			{Key: "name", IsRequired: true},
		}},
		{Name: "PetPatch", Props: []runtime.Prop{
			{Key: "age"},
			{Key: "legacy"},
			{Key: "name"},
			{Key: "nickname", IsNullable: true},
			{Key: "owner", IsNullable: true, Object: "Owner"},
			{Key: "tag", IsNullable: true},
			{Key: "toys", Items: &runtime.Prop{}},
		}},
	},
}

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
	Presence           runtime.PresenceChecker
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
		Presence:           bodyPresence,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// WithPresence sets what checks the keys of request bodies and fills their defaults.
func WithPresence(p runtime.PresenceChecker) ServerOption {
	return func(o *ServerOptions) {
		o.Presence = p
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// UpdatePet handles PATCH /pets/{id}.
func (a *HTTPAdapter) UpdatePet(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "UpdatePet"))
	opts := &UpdatePetServiceRequestOptions{RawRequest: r}
	query := r.URL.Query()
	opts.PathParams = &UpdatePetPathParams{}
	if err := runtime.DecodePath(runtime.UnescapePath(r, chi.URLParam(r, "id")), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "UpdatePet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	opts.Query = &UpdatePetQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "notify", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Notify); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "UpdatePet", ParamName: "notify", ParamLocation: "query", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		body, err := a.opts.Presence.JSON(r.Body, runtime.Prop{Object: "PetPatch"})
		if err != nil {
			a.failBody(w, r, "UpdatePet", err)
			return
		}
		if err = a.opts.JSONDecoder(body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "UpdatePet", err)
			return
		}
	case "":
		a.failDecode(w, r, "UpdatePet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "UpdatePet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "UpdatePet", Err: err})
		return
	}

	res, err := a.svc.UpdatePet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "UpdatePet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "UpdatePet", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "UpdatePet", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) failBody(w http.ResponseWriter, r *http.Request, id string, err error) {
	kind := runtime.ErrorDecode
	if runtime.IsValidation(err) {
		kind = runtime.ErrorValidation
	}
	a.fail(w, r, &runtime.HandlerError{Kind: kind, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Patch("/pets/{id}", a.UpdatePet)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}

// UpdatePetRequestOptions is what UpdatePet sends.
type UpdatePetRequestOptions struct {
	PathParams *UpdatePetPathParams
	Query      *UpdatePetQuery
	// Body sent as application/json.
	Body *PetPatch
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *UpdatePetRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// UpdatePet calls PATCH /pets/{id}.
	UpdatePet(ctx context.Context, opts *UpdatePetRequestOptions, editors ...RequestEditor) (*Pet, error)
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *runtime.APIError.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// UpdatePet calls PATCH /pets/{id}.
func (c *Client) UpdatePet(ctx context.Context, opts *UpdatePetRequestOptions, editors ...RequestEditor) (*Pet, error) {
	req, err := c.UpdatePetRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Pet
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// UpdatePetRequest builds the request of PATCH /pets/{id}.
func (c *Client) UpdatePetRequest(ctx context.Context, opts *UpdatePetRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &UpdatePetRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPatch, "/pets/{id}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.ID, runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
	}
	if opts.Query != nil {
		b.QueryParam(opts.Query.Notify, runtime.Param{Name: "notify", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false})
	}
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json")
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "UpdatePet", b, editors)
}

func (c *Client) newRequest(ctx context.Context, id string, b *runtime.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	ctx = runtime.WithOperationID(ctx, id)
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
