// Code generated by mockzilla-codegen. DO NOT EDIT.

package models

import (
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Order struct {
	ID     string `json:"id"`
	Status Status `json:"status"`
	Items  []Item `json:"items,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (o Order) Validate() error {
	var errs validation.Errors
	errs.Append("status", o.Status.Validate())
	for idx, item := range o.Items {
		errs.Append(validation.Index("items", idx), item.Validate())
	}
	return errs.Err()
}

type Item struct {
	Sku      string `json:"sku"`
	Quantity int    `json:"quantity"`
}

// Validate checks the value against the constraints of the spec.
func (i Item) Validate() error {
	var errs validation.Errors
	errs.Append("quantity", validation.Minimum(i.Quantity, 1, false))
	return errs.Err()
}

type Problem struct {
	Detail string `json:"detail"`
}

type Status string

const (
	StatusOpen    Status = "open"
	StatusPaid    Status = "paid"
	StatusShipped Status = "shipped"
)

// StatusValues returns the values of Status.
func StatusValues() []Status {
	return []Status{
		StatusOpen,
		StatusPaid,
		StatusShipped,
	}
}

// Validate checks the value against the constraints of the spec.
func (s Status) Validate() error {
	return validation.Enum(s, StatusOpen, StatusPaid, StatusShipped)
}

type GetOrderQueryExpand string

const (
	GetOrderQueryExpandItems    GetOrderQueryExpand = "items"
	GetOrderQueryExpandCustomer GetOrderQueryExpand = "customer"
)

// GetOrderQueryExpandValues returns the values of GetOrderQueryExpand.
func GetOrderQueryExpandValues() []GetOrderQueryExpand {
	return []GetOrderQueryExpand{
		GetOrderQueryExpandItems,
		GetOrderQueryExpandCustomer,
	}
}

// Validate checks the value against the constraints of the spec.
func (g GetOrderQueryExpand) Validate() error {
	return validation.Enum(g, GetOrderQueryExpandItems, GetOrderQueryExpandCustomer)
}

type GetOrderPathParams struct {
	ID string `json:"id"`
}

type GetOrderQuery struct {
	Expand *GetOrderQueryExpand `json:"expand,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (g GetOrderQuery) Validate() error {
	var errs validation.Errors
	if g.Expand != nil {
		errs.Append("expand", g.Expand.Validate())
	}
	return errs.Err()
}

type CreateOrderRequestBody struct {
	Items []Item `json:"items"`
}

// Validate checks the value against the constraints of the spec.
func (c CreateOrderRequestBody) Validate() error {
	var errs validation.Errors
	if c.Items == nil {
		errs.Required("items")
	}
	for idx, item := range c.Items {
		errs.Append(validation.Index("items", idx), item.Validate())
	}
	return errs.Err()
}
