// Code generated by mockzilla-codegen. DO NOT EDIT.

package rules

import (
	"regexp"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

var (
	patternItemCode = regexp.MustCompile(`^[A-Z]{3}$`)
	patternItemWord = regexp.MustCompile(`^[^\t-\r \xA0\x{1680}\x{2000}-\x{200A}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}\x{FEFF}]+$`)
	patternItemLine = regexp.MustCompile(`^[^\n\r\x{2028}\x{2029}]*$`)
	patternItemRef  = regexp.MustCompile(`^[A-Z]`)
	patternItemRef2 = regexp.MustCompile(`[0-9]$`)
)

type Code = string

type Corner struct {
	X *int `json:"x,omitempty"`
	Y *int `json:"y,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (c Corner) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.OneOfJSON(c, `{"x":0,"y":null}`, `{"x":1,"y":1}`))
	return errs.Err()
}

type Item struct {
	Name   string            `json:"name"`
	Code   Code              `json:"code"`
	ID     *string           `json:"id,omitempty"`
	Site   *string           `json:"site,omitempty"`
	Host   *string           `json:"host,omitempty"`
	Email  *runtime.Email    `json:"email,omitempty"`
	Price  *float64          `json:"price,omitempty"`
	Count  *int              `json:"count,omitempty"`
	Tags   []string          `json:"tags"`
	Labels map[string]string `json:"labels,omitempty"`
	Kind   *string           `json:"kind,omitempty"`
	Size   *Size             `json:"size,omitempty"`
	Corner *Corner           `json:"corner,omitempty"`
	Dims   []int             `json:"dims,omitempty"`
	Unit   *ItemUnit         `json:"unit,omitempty"`
	Mark   any               `json:"mark,omitempty"`
	Token  []byte            `json:"token,omitempty"`
	Word   *string           `json:"word,omitempty"`
	Line   *string           `json:"line,omitempty"`
	Stock  *int              `json:"stock,omitempty"`
	Ref    *string           `json:"ref,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (i Item) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("name", runtime.MinLength(i.Name, 2))
	errs.Append("name", runtime.MaxLength(i.Name, 10))
	errs.Append("code", runtime.Pattern(i.Code, patternItemCode, `^[A-Z]{3}$`))
	if i.ID != nil {
		errs.Append("id", runtime.Format(*i.ID, "uuid"))
	}
	if i.Site != nil {
		errs.Append("site", runtime.Format(*i.Site, "uri"))
	}
	if i.Host != nil {
		errs.Append("host", runtime.Format(*i.Host, "hostname"))
	}
	if i.Email != nil {
		errs.Append("email", i.Email.Validate())
	}
	if i.Price != nil {
		errs.Append("price", runtime.Minimum(*i.Price, 0, false))
		errs.Append("price", runtime.Maximum(*i.Price, 1000, true))
		errs.Append("price", runtime.MultipleOf(*i.Price, 0.01))
	}
	if i.Count != nil {
		errs.Append("count", runtime.Minimum(*i.Count, 0, true))
		errs.Append("count", runtime.Maximum(*i.Count, 5, false))
	}
	if i.Tags == nil {
		errs.Required("tags")
	}
	if i.Tags != nil {
		errs.Append("tags", runtime.MinItems(i.Tags, 1))
		errs.Append("tags", runtime.MaxItems(i.Tags, 3))
		errs.Append("tags", runtime.Unique(i.Tags))
		for idx, item := range i.Tags {
			errs.Append(runtime.Index("tags", idx), runtime.MaxLength(item, 5))
		}
	}
	if i.Labels != nil {
		errs.Append("labels", runtime.MaxProperties(i.Labels, 2))
		for _, key := range runtime.SortedKeys(i.Labels) {
			item := i.Labels[key]
			errs.Append(runtime.Key("labels", key), runtime.MinLength(item, 1))
		}
	}
	if i.Kind != nil {
		errs.Append("kind", runtime.Const(*i.Kind, "item"))
	}
	if i.Size != nil {
		errs.Append("size", i.Size.Validate())
	}
	if i.Corner != nil {
		errs.Append("corner", i.Corner.Validate())
	}
	if i.Dims != nil {
		errs.Append("dims", runtime.OneOfJSON(i.Dims, `[1,2]`, `[2,4]`))
	}
	if i.Unit != nil {
		errs.Append("unit", i.Unit.Validate())
	}
	if i.Mark != nil {
		errs.Append("mark", runtime.OneOfJSON(i.Mark, `"a"`, `1`, `true`))
	}
	if i.Token != nil {
		errs.Append("token", runtime.MaxLength(runtime.Base64(i.Token), 8))
	}
	if i.Word != nil {
		errs.Append("word", runtime.Pattern(*i.Word, patternItemWord, `^\S+$`))
	}
	if i.Line != nil {
		errs.Append("line", runtime.Pattern(*i.Line, patternItemLine, `^.*$`))
	}
	if i.Stock != nil {
		errs.Append("stock", runtime.Minimum(*i.Stock, 10, false))
		errs.Append("stock", runtime.Maximum(*i.Stock, 100, false))
	}
	if i.Ref != nil {
		errs.Append("ref", runtime.Pattern(*i.Ref, patternItemRef, `^[A-Z]`))
		errs.Append("ref", runtime.Pattern(*i.Ref, patternItemRef2, `[0-9]$`))
	}
	return errs.Err()
}

type Size string

const (
	SizeS Size = "s"
	SizeM Size = "m"
	SizeL Size = "l"
)

// SizeValues returns the values of Size.
func SizeValues() []Size {
	return []Size{
		SizeS,
		SizeM,
		SizeL,
	}
}

// Validate checks the value against the constraints of the spec.
func (s Size) Validate() error {
	return runtime.OneOf(s, SizeS, SizeM, SizeL)
}

// ItemUnit is one of String or Int.
type ItemUnit struct {
	String *string `json:"-"`
	Int    *int    `json:"-"`
}

// MarshalJSON writes the variant that is set.
func (i ItemUnit) MarshalJSON() ([]byte, error) {
	var set []any
	if i.String != nil {
		set = append(set, i.String)
	}
	if i.Int != nil {
		set = append(set, i.Int)
	}
	return runtime.MarshalOneOf(nil, set...)
}

// UnmarshalJSON sets the variant data matches.
func (i *ItemUnit) UnmarshalJSON(data []byte) error {
	*i = ItemUnit{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		Variants: []runtime.Variant{
			{
				Name: "String",
				Kind: runtime.KindString,
				Into: runtime.Into(&i.String),
			},
			{
				Name: "Int",
				Kind: runtime.KindInteger,
				Into: runtime.Into(&i.Int),
			},
		},
	})
}

// MarshalText writes the variant that is set as text.
func (i ItemUnit) MarshalText() ([]byte, error) {
	return runtime.MarshalUnionText(i.MarshalJSON())
}

// UnmarshalText sets the variant text matches.
func (i *ItemUnit) UnmarshalText(text []byte) error {
	return runtime.UnmarshalUnionText(text, i.UnmarshalJSON)
}

// Validate checks the value against the constraints of the spec.
func (i ItemUnit) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.ExactlyOne(i.String != nil, i.Int != nil))
	errs.Append("", runtime.OneOfJSON(i, `"cm"`, `10`))
	return errs.Err()
}
