// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol"
)

// WithRouter registers the routes on h instead of a new Hertz.
func WithRouter(h *server.Hertz) ServerOption {
	return func(o *ServerOptions) {
		o.Router = h
	}
}

// NewRouter registers every operation on a Hertz server. On a new server the middleware
// WithMiddleware adds wraps everything, unknown paths too; on the server WithRouter gives it, the
// middleware wraps each generated route and nothing else.
func NewRouter(svc BooksInterface, opts ...ServerOption) *server.Hertz {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(h *server.Hertz, route func(http.Handler) http.Handler) {
		h.GET("/books/:isbn", handle(route(http.HandlerFunc(adapter.GetBook))))
	}

	if h, _ := o.Router.(*server.Hertz); h != nil {
		register(h, wrap)
		return h
	}
	h := server.New()
	register(h, wrap)
	h.NoRoute(handle(wrap(http.NotFoundHandler())))
	return h
}

// handle serves h as a hertz handler: the request is read into an http.Request, with the path
// parameters hertz found, and the response is written into hertz's.
func handle(h http.Handler) app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		r, err := http.NewRequestWithContext(ctx, string(c.Method()), string(c.URI().FullURI()), bytes.NewReader(c.Request.Body()))
		if err != nil {
			c.AbortWithMsg(err.Error(), http.StatusBadRequest)
			return
		}
		c.Request.Header.VisitAll(func(key, value []byte) {
			r.Header.Add(string(key), string(value))
		})
		for _, p := range c.Params {
			r.SetPathValue(p.Key, p.Value)
		}
		r.RemoteAddr = c.RemoteAddr().String()
		h.ServeHTTP(&responseWriter{response: &c.Response, header: http.Header{}}, r)
	}
}

// responseWriter is an http.ResponseWriter over a hertz response: the headers go over with the
// status, on the first write at the latest.
type responseWriter struct {
	response  *protocol.Response
	header    http.Header
	isWritten bool
}

func (w *responseWriter) Header() http.Header {
	return w.header
}

func (w *responseWriter) WriteHeader(status int) {
	if w.isWritten {
		return
	}
	w.isWritten = true
	for key, values := range w.header {
		for _, value := range values {
			w.response.Header.Add(key, value)
		}
	}
	w.response.SetStatusCode(status)
}

func (w *responseWriter) Write(b []byte) (int, error) {
	if !w.isWritten {
		w.WriteHeader(http.StatusOK)
	}
	return w.response.BodyWriter().Write(b)
}
