// Code generated by mockzilla-codegen. DO NOT EDIT.

package params

import (
	"context"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime package does not match the mockzilla-codegen version that
// wrote this file.
const _ = runtime.SupportsGeneratorV2

type Point struct {
	X *int `json:"x,omitempty"`
	Y *int `json:"y,omitempty"`
}

type Filter struct {
	Name *string  `json:"name,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Size *Point   `json:"size,omitempty"`
}

type Echo map[string]any

type PathStylesPathParams struct {
	Simple string   `json:"simple"`
	Label  int      `json:"label"`
	Matrix bool     `json:"matrix"`
	List   []string `json:"list"`
}

// Validate checks the value against the constraints of the spec.
func (p PathStylesPathParams) Validate() error {
	var errs runtime.ValidationErrors
	if p.List == nil {
		errs.Add("list", "is required")
	}
	return errs.Err()
}

type QueryStylesQuery struct {
	Form   []int    `json:"form,omitempty"`
	Csv    []string `json:"csv,omitempty"`
	Space  []string `json:"space,omitempty"`
	Pipe   []string `json:"pipe,omitempty"`
	Deep   *Point   `json:"deep,omitempty"`
	Flat   *Point   `json:"flat,omitempty"`
	JSON   *Point   `json:"json,omitempty"`
	Filter *Filter  `json:"filter,omitempty"`
	Where  *Filter  `json:"where,omitempty"`
	Needed string   `json:"needed"`
}

type HeaderStylesHeaders struct {
	XTags  []string   `json:"X-Tags,omitempty"`
	XPoint *Point     `json:"X-Point,omitempty"`
	XWhen  *time.Time `json:"X-When,omitempty"`
}

type CookieStylesCookies struct {
	Session *string `json:"session,omitempty"`
	Flags   []int   `json:"flags,omitempty"`
}

// PathStylesRequestOptions is what PathStyles sends.
type PathStylesRequestOptions struct {
	PathParams *PathStylesPathParams
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PathStylesRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.PathParams != nil {
		errs.Append("path", o.PathParams.Validate())
	}
	return errs.Err()
}

// QueryStylesRequestOptions is what QueryStyles sends.
type QueryStylesRequestOptions struct {
	Query *QueryStylesQuery
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *QueryStylesRequestOptions) Validate() error {
	return nil
}

// HeaderStylesRequestOptions is what HeaderStyles sends.
type HeaderStylesRequestOptions struct {
	Headers *HeaderStylesHeaders
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *HeaderStylesRequestOptions) Validate() error {
	return nil
}

// CookieStylesRequestOptions is what CookieStyles sends.
type CookieStylesRequestOptions struct {
	Cookies *CookieStylesCookies
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CookieStylesRequestOptions) Validate() error {
	return nil
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// PathStyles calls GET /path/{simple}/{label}/{matrix}/{list}.
	PathStyles(ctx context.Context, opts *PathStylesRequestOptions, editors ...RequestEditor) (Echo, error)
	// QueryStyles calls GET /query.
	QueryStyles(ctx context.Context, opts *QueryStylesRequestOptions, editors ...RequestEditor) (Echo, error)
	// HeaderStyles calls GET /header.
	HeaderStyles(ctx context.Context, opts *HeaderStylesRequestOptions, editors ...RequestEditor) (Echo, error)
	// CookieStyles calls GET /cookie.
	CookieStyles(ctx context.Context, opts *CookieStylesRequestOptions, editors ...RequestEditor) (Echo, error)
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *runtime.APIError.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// PathStyles calls GET /path/{simple}/{label}/{matrix}/{list}.
func (c *Client) PathStyles(ctx context.Context, opts *PathStylesRequestOptions, editors ...RequestEditor) (Echo, error) {
	req, err := c.PathStylesRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out Echo
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// PathStylesRequest builds the request of GET /path/{simple}/{label}/{matrix}/{list}.
func (c *Client) PathStylesRequest(ctx context.Context, opts *PathStylesRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &PathStylesRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/path/{simple}/{label}/{matrix}/{list}")
	if opts.PathParams != nil {
		b.PathParam(opts.PathParams.Simple, runtime.Param{Name: "simple", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false})
		b.PathParam(opts.PathParams.Label, runtime.Param{Name: "label", Style: runtime.StyleLabel, IsExplode: false, IsRequired: true, IsJSON: false})
		b.PathParam(opts.PathParams.Matrix, runtime.Param{Name: "matrix", Style: runtime.StyleMatrix, IsExplode: false, IsRequired: true, IsJSON: false})
		b.PathParam(opts.PathParams.List, runtime.Param{Name: "list", Style: runtime.StyleSimple, IsExplode: true, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, b, editors)
}

// QueryStyles calls GET /query.
func (c *Client) QueryStyles(ctx context.Context, opts *QueryStylesRequestOptions, editors ...RequestEditor) (Echo, error) {
	req, err := c.QueryStylesRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out Echo
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// QueryStylesRequest builds the request of GET /query.
func (c *Client) QueryStylesRequest(ctx context.Context, opts *QueryStylesRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &QueryStylesRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/query")
	if opts.Query != nil {
		b.QueryParam(opts.Query.Form, runtime.Param{Name: "form", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Csv, runtime.Param{Name: "csv", Style: runtime.StyleForm, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Space, runtime.Param{Name: "space", Style: runtime.StyleSpaceDelimited, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Pipe, runtime.Param{Name: "pipe", Style: runtime.StylePipeDelimited, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Deep, runtime.Param{Name: "deep", Style: runtime.StyleDeepObject, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Flat, runtime.Param{Name: "flat", Style: runtime.StyleForm, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.JSON, runtime.Param{Name: "json", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: true})
		b.QueryParam(opts.Query.Filter, runtime.Param{Name: "filter", Style: runtime.StyleDeepObject, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Where, runtime.Param{Name: "where", Style: runtime.StyleForm, IsExplode: false, IsRequired: false, IsJSON: false})
		b.QueryParam(opts.Query.Needed, runtime.Param{Name: "needed", Style: runtime.StyleForm, IsExplode: true, IsRequired: true, IsJSON: false})
	}
	return c.newRequest(ctx, b, editors)
}

// HeaderStyles calls GET /header.
func (c *Client) HeaderStyles(ctx context.Context, opts *HeaderStylesRequestOptions, editors ...RequestEditor) (Echo, error) {
	req, err := c.HeaderStylesRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out Echo
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// HeaderStylesRequest builds the request of GET /header.
func (c *Client) HeaderStylesRequest(ctx context.Context, opts *HeaderStylesRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &HeaderStylesRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/header")
	if opts.Headers != nil {
		b.HeaderParam(opts.Headers.XTags, runtime.Param{Name: "X-Tags", Style: runtime.StyleSimple, IsExplode: false, IsRequired: false, IsJSON: false})
		b.HeaderParam(opts.Headers.XPoint, runtime.Param{Name: "X-Point", Style: runtime.StyleSimple, IsExplode: false, IsRequired: false, IsJSON: false})
		b.HeaderParam(opts.Headers.XWhen, runtime.Param{Name: "X-When", Style: runtime.StyleSimple, IsExplode: false, IsRequired: false, IsJSON: false})
	}
	return c.newRequest(ctx, b, editors)
}

// CookieStyles calls GET /cookie.
func (c *Client) CookieStyles(ctx context.Context, opts *CookieStylesRequestOptions, editors ...RequestEditor) (Echo, error) {
	req, err := c.CookieStylesRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out Echo
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// CookieStylesRequest builds the request of GET /cookie.
func (c *Client) CookieStylesRequest(ctx context.Context, opts *CookieStylesRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &CookieStylesRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodGet, "/cookie")
	if opts.Cookies != nil {
		b.CookieParam(opts.Cookies.Session, runtime.Param{Name: "session", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false})
		b.CookieParam(opts.Cookies.Flags, runtime.Param{Name: "flags", Style: runtime.StyleForm, IsExplode: false, IsRequired: false, IsJSON: false})
	}
	return c.newRequest(ctx, b, editors)
}

func (c *Client) newRequest(ctx context.Context, b *runtime.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
