// Code generated by mockzilla-codegen. DO NOT EDIT.

package errors

import (
	"context"
	"io"
	"net/http"
	"strings"

	fiber "github.com/gofiber/fiber/v3"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/valyala/fasthttp/fasthttpadaptor"
)

// Fails to compile when the runtime package does not match the mockzilla-codegen version that
// wrote this file.
const _ = runtime.SupportsGeneratorV2

type Pet struct {
	Name string `json:"name"`
	Age  *int   `json:"age,omitempty"`
}

// Validate checks the value against the constraints of the spec, as a request carries it.
func (p Pet) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("name", runtime.MinLength(p.Name, 1))
	return errs.Err()
}

// ValidateResponse checks the value against the constraints of the spec, as a response carries it.
func (p Pet) ValidateResponse() error {
	var errs runtime.ValidationErrors
	errs.Append("name", runtime.MinLength(p.Name, 1))
	if p.Age != nil {
		errs.Append("age", runtime.Minimum(*p.Age, 0, false))
	}
	return errs.Err()
}

type Problem struct {
	Detail string `json:"detail"`
}

// Error returns the message at detail.
func (p Problem) Error() string {
	return runtime.ErrorMessage(p, "detail", "Problem")
}

// NewProblem returns a Problem with message at detail.
func NewProblem(message string) Problem {
	var p Problem
	_ = runtime.SetErrorMessage(&p, "detail", message)
	return p
}

type Locked struct {
	Detail *string `json:"detail,omitempty"`
	Until  *string `json:"until,omitempty"`
}

type GetPetQueryFieldsItem string

const (
	GetPetQueryFieldsItemName GetPetQueryFieldsItem = "name"
	GetPetQueryFieldsItemAge  GetPetQueryFieldsItem = "age"
)

// Validate checks the value against the constraints of the spec.
func (g GetPetQueryFieldsItem) Validate() error {
	return runtime.OneOf(g, GetPetQueryFieldsItemName, GetPetQueryFieldsItemAge)
}

type GetPetPathParams struct {
	ID int `json:"id"`
}

// Validate checks the value against the constraints of the spec.
func (g GetPetPathParams) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("id", runtime.Minimum(g.ID, 1, false))
	return errs.Err()
}

type GetPetQuery struct {
	Fields []GetPetQueryFieldsItem `json:"fields,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (g GetPetQuery) Validate() error {
	var errs runtime.ValidationErrors
	for idx, item := range g.Fields {
		errs.Append(runtime.Index("fields", idx), item.Validate())
	}
	return errs.Err()
}

type PutPetPathParams struct {
	ID int `json:"id"`
}

// Validate checks the value against the constraints of the spec.
func (p PutPetPathParams) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("id", runtime.Minimum(p.ID, 1, false))
	return errs.Err()
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// GetPet handles GET /pets/{id}.
	GetPet(ctx context.Context, opts *GetPetServiceRequestOptions) (*GetPetResponseData, error)
	// PutPet handles PUT /pets/{id}.
	PutPet(ctx context.Context, opts *PutPetServiceRequestOptions) (*PutPetResponseData, error)
}

// GetPetServiceRequestOptions is what GetPet receives. RawRequest is the request as it came in.
type GetPetServiceRequestOptions struct {
	PathParams *GetPetPathParams
	Query      *GetPetQuery
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *GetPetServiceRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.PathParams != nil {
		errs.Append("path", o.PathParams.Validate())
	}
	if o.Query != nil {
		errs.Append("query", o.Query.Validate())
	}
	return errs.Err()
}

// GetPetResponseData is what GetPet returns: the status, the headers and the body of the response.
type GetPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewGetPetResponseData200 returns the response data of status 200 with body as application/json.
func NewGetPetResponseData200(body *Pet) *GetPetResponseData {
	return &GetPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// NewGetPetResponseData404 returns the response data of status 404 with body as application/problem+json.
func NewGetPetResponseData404(body *Problem) *GetPetResponseData {
	return &GetPetResponseData{Status: 404, Body: body, contentType: "application/problem+json"}
}

// NewGetPetResponseData409 returns the response data of status 409 with body as application/problem+json.
func NewGetPetResponseData409(body *Locked) *GetPetResponseData {
	return &GetPetResponseData{Status: 409, Body: body, contentType: "application/problem+json"}
}

// WithStatus sets the status code.
func (r *GetPetResponseData) WithStatus(code int) *GetPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *GetPetResponseData) WithHeaders(h http.Header) *GetPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *GetPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *GetPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *GetPetResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *GetPetResponseData) ContentType() string {
	return r.contentType
}

// PutPetServiceRequestOptions is what PutPet receives. RawRequest is the request as it came in.
type PutPetServiceRequestOptions struct {
	PathParams *PutPetPathParams
	// Body sent as application/json.
	Body       *Pet
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *PutPetServiceRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.PathParams != nil {
		errs.Append("path", o.PathParams.Validate())
	}
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// PutPetResponseData is what PutPet returns: the status, the headers and the body of the response.
type PutPetResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewPutPetResponseData returns the response data of status 200 with body as application/json.
func NewPutPetResponseData(body *Pet) *PutPetResponseData {
	return &PutPetResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *PutPetResponseData) WithStatus(code int) *PutPetResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *PutPetResponseData) WithHeaders(h http.Header) *PutPetResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *PutPetResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *PutPetResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *PutPetResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *PutPetResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with. Router is the router the
// routes go on when one is given; Middleware wraps the routes, outermost first; ErrorHandler
// writes the response of a failed request; JSONDecoder reads JSON bodies.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first, after any middleware added before.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory before parts spill to
// disk.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service: one handler per operation.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

// responseData is what every response data type gives the adapter.
type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// GetPet handles GET /pets/{id}.
func (a *HTTPAdapter) GetPet(w http.ResponseWriter, r *http.Request) {
	opts := &GetPetServiceRequestOptions{RawRequest: r}
	query := r.URL.Query()
	opts.PathParams = &GetPetPathParams{}
	if err := runtime.DecodePath(r.PathValue("id"), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetPet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	opts.Query = &GetPetQuery{}
	if err := runtime.DecodeQuery(query, runtime.Param{Name: "fields", Style: runtime.StyleForm, IsExplode: true, IsRequired: false, IsJSON: false}, &opts.Query.Fields); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "GetPet", ParamName: "fields", ParamLocation: "query", Err: err})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "GetPet", Err: err})
		return
	}

	res, err := a.svc.GetPet(r.Context(), opts)
	if err != nil {
		if problem, ok := runtime.AsError[Problem](err); ok {
			a.opts.ErrorHandler.HandleError(w, r, 404, problem)
			return
		}
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "GetPet", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "GetPet", res)
}

// PutPet handles PUT /pets/{id}.
func (a *HTTPAdapter) PutPet(w http.ResponseWriter, r *http.Request) {
	opts := &PutPetServiceRequestOptions{RawRequest: r}
	opts.PathParams = &PutPetPathParams{}
	if err := runtime.DecodePath(r.PathValue("id"), runtime.Param{Name: "id", Style: runtime.StyleSimple, IsExplode: false, IsRequired: true, IsJSON: false}, &opts.PathParams.ID); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorParse, OperationID: "PutPet", ParamName: "id", ParamLocation: "path", Err: err})
		return
	}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "PutPet", err)
			return
		}
	case "":
		a.failDecode(w, r, "PutPet", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "PutPet", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}
	if err := opts.Validate(); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorValidation, OperationID: "PutPet", Err: err})
		return
	}

	res, err := a.svc.PutPet(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutPet", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "PutPet", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "PutPet", res)
}

// fail answers a request the handler could not serve.
func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

// failDecode answers a request whose body could not be read.
func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

// write writes the response of the service, once it passes the checks of the spec.
func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if err := runtime.ValidateResponse(res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorResponse, OperationID: id, Err: err})
		return
	}
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	if err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on app instead of a new App.
func WithRouter(app *fiber.App) ServerOption {
	return func(o *ServerOptions) {
		o.Router = app
	}
}

// NewRouter registers every operation on a fiber App. On a new App the middleware
// WithMiddleware adds wraps everything, and a request no route takes, by path or by method, is
// a 404 through it; on the App WithRouter gives it, the middleware wraps each generated route
// and nothing else.
func NewRouter(svc ServiceInterface, opts ...ServerOption) *fiber.App {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	wrap := func(h http.Handler) http.Handler {
		for i := len(o.Middleware) - 1; i >= 0; i-- {
			h = o.Middleware[i](h)
		}
		return h
	}
	register := func(app *fiber.App, route func(http.Handler) http.Handler) {
		app.Get("/pets/:id", handle(route(http.HandlerFunc(adapter.GetPet))))
		app.Put("/pets/:id", handle(route(http.HandlerFunc(adapter.PutPet))))
	}

	if app, _ := o.Router.(*fiber.App); app != nil {
		register(app, wrap)
		return app
	}
	app := fiber.New()
	register(app, wrap)
	app.Use(handle(wrap(http.NotFoundHandler())))
	return app
}

// handle serves h as a fiber handler, with the path parameters fiber found on the request. The
// request is copied out of fiber's, whose strings live for the request alone.
func handle(h http.Handler) fiber.Handler {
	return func(c fiber.Ctx) error {
		fasthttpadaptor.NewFastHTTPHandler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			for _, name := range c.Route().Params {
				r.SetPathValue(name, strings.Clone(c.Params(name)))
			}
			h.ServeHTTP(w, r)
		}))(c.RequestCtx())
		return nil
	}
}
