// Code generated by mockzilla-codegen. DO NOT EDIT.

package nullable

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/url"
	"slices"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpclient"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/mcptool"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/validation"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type Pet struct {
	Name string `json:"name"`
}

type Adoption struct {
	Family string `json:"family"`
	// The pet, or null while the family has not chosen one.
	Pet      *Pet              `json:"pet,omitempty"`
	Priority *AdoptionPriority `json:"priority,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (a Adoption) Validate() error {
	var errs validation.Errors
	if a.Priority != nil {
		errs.Append("priority", a.Priority.Validate())
	}
	return errs.Err()
}

type AdoptionPriority string

const (
	AdoptionPriorityHigh AdoptionPriority = "high"
	AdoptionPriorityLow  AdoptionPriority = "low"
)

// AdoptionPriorityValues returns the values of AdoptionPriority.
func AdoptionPriorityValues() []AdoptionPriority {
	return []AdoptionPriority{
		AdoptionPriorityHigh,
		AdoptionPriorityLow,
	}
}

// Validate checks the value against the constraints of the spec.
func (a AdoptionPriority) Validate() error {
	return validation.Enum(a, AdoptionPriorityHigh, AdoptionPriorityLow)
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// Adopt handles POST /adoptions.
	// Record an adoption
	Adopt(ctx context.Context, opts *AdoptServiceRequestOptions) (*AdoptResponseData, error)
}

// AdoptServiceRequestOptions is what Adopt receives.
type AdoptServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *Adoption
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AdoptServiceRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// AdoptResponseData is what Adopt returns.
type AdoptResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewAdoptResponseData returns the 200 response with its application/json body.
func NewAdoptResponseData(body *Adoption) *AdoptResponseData {
	return &AdoptResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *AdoptResponseData) WithStatus(code int) *AdoptResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *AdoptResponseData) WithHeaders(h http.Header) *AdoptResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *AdoptResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *AdoptResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *AdoptResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *AdoptResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       httpserver.ErrorHandler
	JSONDecoder        func(data []byte, v any) error
	JSONEncoder        func(v any) ([]byte, error)
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// Adopt handles POST /adoptions.
func (a *HTTPAdapter) Adopt(w http.ResponseWriter, r *http.Request) {
	r = r.WithContext(runtime.WithOperationID(r.Context(), "Adopt"))
	opts := &AdoptServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.Body, true, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "Adopt", err)
			return
		}
	case "":
		a.failDecode(w, r, "Adopt", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "Adopt", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.Adopt(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "Adopt", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "Adopt", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "Adopt", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/adoptions", a.Adopt)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}

// AdoptRequestOptions is what Adopt sends.
type AdoptRequestOptions struct {
	// Body sent as application/json.
	Body *Adoption
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AdoptRequestOptions) Validate() error {
	var errs validation.Errors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = httpclient.Doer

// RequestEditor changes a request before it is sent.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientInterface is what Client implements.
type ClientInterface interface {
	// Adopt calls POST /adoptions.
	// Record an adoption
	Adopt(ctx context.Context, opts *AdoptRequestOptions, editors ...RequestEditor) (*Adoption, error)
}

var _ ClientInterface = (*Client)(nil)

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// WithHTTPClient sends the requests with d. A nil d panics.
func WithHTTPClient(d HTTPDoer) ClientOption {
	if d == nil {
		panic("WithHTTPClient: nil HTTPDoer")
	}
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent. A nil one panics.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	for _, fn := range fns {
		if fn == nil {
			panic("WithRequestEditor: nil RequestEditor")
		}
	}
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// WithJSON writes JSON bodies with marshal and reads them with unmarshal. A nil one panics.
func WithJSON(marshal func(v any) ([]byte, error), unmarshal func(data []byte, v any) error) ClientOption {
	if marshal == nil || unmarshal == nil {
		panic("WithJSON: nil function")
	}
	return func(c *Client) {
		c.marshal, c.unmarshal = marshal, unmarshal
	}
}

// Client calls the API at a base URL.
// A response outside 2xx, or a 2xx the spec does not list, is a *httpclient.APIError.
type Client struct {
	baseURL   *url.URL
	doer      HTTPDoer
	timeout   time.Duration
	editors   []RequestEditor
	marshal   func(v any) ([]byte, error)
	unmarshal func(data []byte, v any) error
}

// NewClient returns a client of the API at baseURL.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := httpclient.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{
		baseURL:   u,
		doer:      &http.Client{},
		timeout:   3 * time.Second,
		marshal:   json.Marshal,
		unmarshal: json.Unmarshal,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// Adopt calls POST /adoptions.
// Record an adoption
func (c *Client) Adopt(ctx context.Context, opts *AdoptRequestOptions, editors ...RequestEditor) (*Adoption, error) {
	req, err := c.AdoptRequest(ctx, opts, editors...)
	if err != nil {
		return nil, err
	}
	res, body, err := httpclient.Send(c.doer, req, "application/json", c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Adoption
	if err = httpclient.DecodeSuccess(res, body, []httpclient.ResponseTarget{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}, c.unmarshal); err != nil {
		return nil, err
	}
	return out, nil
}

// AdoptRequest builds the request of POST /adoptions.
func (c *Client) AdoptRequest(ctx context.Context, opts *AdoptRequestOptions, editors ...RequestEditor) (*http.Request, error) {
	if opts == nil {
		opts = &AdoptRequestOptions{}
	}
	b := httpclient.NewRequestBuilder(http.MethodPost, "/adoptions")
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json", c.marshal)
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, "Adopt", b, editors)
}

func (c *Client) newRequest(ctx context.Context, id string, b *httpclient.RequestBuilder, editors []RequestEditor) (*http.Request, error) {
	ctx = runtime.WithOperationID(ctx, id)
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range slices.Concat(c.editors, editors) {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// AdoptToolInput is the input of the adopt tool.
type AdoptToolInput struct {
	// The request body, sent as application/json.
	Body *Adoption `json:"body"`
}

// MCPTools exposes the operations of the API as MCP tools.
type MCPTools struct {
	client ClientInterface
}

// NewMCPTools returns the tools that call c. A nil c panics.
func NewMCPTools(c ClientInterface) *MCPTools {
	if c == nil {
		panic("NewMCPTools: nil client")
	}
	return &MCPTools{client: c}
}

// Register adds every tool to s.
func (t *MCPTools) Register(s *mcp.Server) {
	mcp.AddTool(s, t.AdoptTool(), t.Adopt)
}

// AdoptTool is the definition of the adopt tool.
func (t *MCPTools) AdoptTool() *mcp.Tool {
	return &mcp.Tool{
		Name:        "adopt",
		Description: "Record an adoption",
		InputSchema: json.RawMessage(`{"type":"object","properties":{"body":{"$ref":"#/$defs/Adoption"}},"required":["body"],"additionalProperties":false,"$defs":{"Adoption":{"type":"object","properties":{"family":{"type":"string"},"pet":{"anyOf":[{"allOf":[{"$ref":"#/$defs/Pet"}]},{"type":"null"}],"description":"The pet, or null while the family has not chosen one."},"priority":{"anyOf":[{"type":"string","enum":["high","low"]},{"type":"null"}]}},"required":["family"]},"Pet":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}}`),
		Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: false},
	}
}

// Adopt handles the adopt tool.
func (t *MCPTools) Adopt(ctx context.Context, _ *mcp.CallToolRequest, in AdoptToolInput) (*mcp.CallToolResult, any, error) {
	opts := &AdoptRequestOptions{
		Body: in.Body,
	}
	out, err := t.client.Adopt(ctx, opts)
	if err != nil {
		return nil, nil, mcptool.Error(err)
	}
	return nil, mcptool.Result{Value: out}, nil
}
