// Code generated by mockzilla-codegen. DO NOT EDIT.

package nullable

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"time"

	chi "github.com/go-chi/chi/v5"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// Fails to compile when the runtime package does not match the mockzilla-codegen version that
// wrote this file.
const _ = runtime.SupportsGeneratorV2

type Pet struct {
	Name string `json:"name"`
}

type Adoption struct {
	Family string `json:"family"`
	// The pet, or null while the family has not chosen one.
	Pet      *Pet              `json:"pet,omitempty"`
	Priority *AdoptionPriority `json:"priority,omitempty"`
}

// Validate checks the value against the constraints of the spec.
func (a Adoption) Validate() error {
	var errs runtime.ValidationErrors
	if a.Priority != nil {
		errs.Append("priority", a.Priority.Validate())
	}
	return errs.Err()
}

type AdoptionPriority string

const (
	AdoptionPriorityHigh AdoptionPriority = "high"
	AdoptionPriorityLow  AdoptionPriority = "low"
)

// Validate checks the value against the constraints of the spec.
func (a AdoptionPriority) Validate() error {
	return runtime.OneOf(a, AdoptionPriorityHigh, AdoptionPriorityLow)
}

// ServiceInterface is what the generated handlers call. Implement it with the business logic.
type ServiceInterface interface {
	// Record an adoption
	Adopt(ctx context.Context, opts *AdoptServiceRequestOptions) (*AdoptResponseData, error)
}

// AdoptServiceRequestOptions is what Adopt receives. RawRequest is the request as it came in.
type AdoptServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *Adoption
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AdoptServiceRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// AdoptResponseData is what Adopt returns: the status, the headers and the body of the response.
type AdoptResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewAdoptResponseData returns the response data of status 200 with body as application/json.
func NewAdoptResponseData(body *Adoption) *AdoptResponseData {
	return &AdoptResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *AdoptResponseData) WithStatus(code int) *AdoptResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *AdoptResponseData) WithHeaders(h http.Header) *AdoptResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *AdoptResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *AdoptResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *AdoptResponseData) Payload() any {
	return r.Body
}

// ContentType is the media type the body is written as, empty for the default of its Go type.
func (r *AdoptResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = runtime.ErrorKind
	HandlerError        = runtime.HandlerError
	ErrorHandler        = runtime.ErrorHandler
	ErrorHandlerFunc    = runtime.ErrorHandlerFunc
	DefaultErrorHandler = runtime.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = runtime.ErrorParse
	ErrorDecode     = runtime.ErrorDecode
	ErrorValidation = runtime.ErrorValidation
	ErrorService    = runtime.ErrorService
	ErrorResponse   = runtime.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with. Router is the router the
// routes go on when one is given; Middleware wraps the routes, outermost first; ErrorHandler
// writes the response of a failed request; JSONDecoder reads JSON bodies.
type ServerOptions struct {
	Router             any
	Middleware         []func(http.Handler) http.Handler
	ErrorHandler       runtime.ErrorHandler
	JSONDecoder        func(body io.Reader, dst any, isRequired bool) error
	MultipartMaxMemory int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       runtime.DefaultErrorHandler{},
		JSONDecoder:        runtime.DecodeJSON,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first, after any middleware added before.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h runtime.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON bodies. isRequired says whether an empty body is an error.
func WithJSONDecoder(decode func(body io.Reader, dst any, isRequired bool) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory before parts spill to
// disk.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service: one handler per operation.
type HTTPAdapter struct {
	svc  ServiceInterface
	opts *ServerOptions
}

// responseData is what every response data type gives the adapter.
type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc ServiceInterface, opts ...ServerOption) *HTTPAdapter {
	return &HTTPAdapter{svc: svc, opts: NewServerOptions(opts...)}
}

// Adopt handles POST /adoptions.
func (a *HTTPAdapter) Adopt(w http.ResponseWriter, r *http.Request) {
	opts := &AdoptServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := a.opts.JSONDecoder(r.Body, &opts.Body, true); err != nil {
			a.failDecode(w, r, "Adopt", err)
			return
		}
	case "":
		a.failDecode(w, r, "Adopt", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: "Adopt", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.Adopt(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Adopt", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: "Adopt", Err: runtime.ErrNoResponse})
		return
	}
	a.write(w, r, "Adopt", res)
}

// fail answers a request the handler could not serve.
func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *runtime.HandlerError) {
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

// failDecode answers a request whose body could not be read.
func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorDecode, OperationID: id, Err: err})
}

// write writes the response of the service.
func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	if err := runtime.Write(w, res.StatusCode(), res.Header(), res.Payload()); err != nil {
		a.fail(w, r, &runtime.HandlerError{Kind: runtime.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on r instead of a new router.
func WithRouter(r chi.Router) ServerOption {
	return func(o *ServerOptions) {
		o.Router = r
	}
}

// NewRouter registers every operation on a chi router. On a new router the middleware
// WithMiddleware adds wraps everything, unknown paths too; on the router WithRouter gives it
// wraps the generated routes and nothing else.
func NewRouter(svc ServiceInterface, opts ...ServerOption) chi.Router {
	o := NewServerOptions(opts...)
	adapter := NewHTTPAdapter(svc, opts...)
	register := func(r chi.Router) {
		r.Post("/adoptions", adapter.Adopt)
	}

	router, _ := o.Router.(chi.Router)
	if router == nil {
		router = chi.NewRouter()
		router.Use(o.Middleware...)
		register(router)
		return router
	}
	router.Group(func(r chi.Router) {
		r.Use(o.Middleware...)
		register(r)
	})
	return router
}

// HTTPDoer sends a request, as *http.Client does.
type HTTPDoer = runtime.Doer

// RequestEditor changes a request before it is sent, to add credentials for one.
type RequestEditor func(ctx context.Context, req *http.Request) error

// ClientOption sets one setting of Client.
type ClientOption func(*Client)

// Client calls the API at a base URL, with one method per operation.
type Client struct {
	baseURL *url.URL
	doer    HTTPDoer
	timeout time.Duration
	editors []RequestEditor
}

// NewClient returns a client of the API at baseURL. It sends with an http.Client unless
// WithHTTPClient sets another. A call gives up after 3 * time.Second unless WithTimeout
// sets another limit.
func NewClient(baseURL string, opts ...ClientOption) (*Client, error) {
	u, err := runtime.ParseBaseURL(baseURL)
	if err != nil {
		return nil, err
	}

	c := &Client{baseURL: u, doer: &http.Client{}, timeout: 3 * time.Second}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// WithHTTPClient sends the requests with d, such as an http.Client set up for the API.
func WithHTTPClient(d HTTPDoer) ClientOption {
	return func(c *Client) {
		c.doer = d
	}
}

// WithTimeout sets how long a call may take, 0 for no limit.
func WithTimeout(d time.Duration) ClientOption {
	return func(c *Client) {
		c.timeout = d
	}
}

// WithRequestEditor runs fns on every request before it is sent, after any editor added before.
func WithRequestEditor(fns ...RequestEditor) ClientOption {
	return func(c *Client) {
		c.editors = append(c.editors, fns...)
	}
}

// newRequest builds b against the base URL and runs the editors on the request.
func (c *Client) newRequest(ctx context.Context, b *runtime.RequestBuilder) (*http.Request, error) {
	req, err := b.Build(ctx, c.baseURL)
	if err != nil {
		return nil, err
	}
	for _, edit := range c.editors {
		if err = edit(ctx, req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// AdoptRequestOptions is what Adopt sends: its parameters by location, and its body.
type AdoptRequestOptions struct {
	// Body sent as application/json.
	Body *Adoption
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *AdoptRequestOptions) Validate() error {
	var errs runtime.ValidationErrors
	if o.Body != nil {
		errs.Append("body", o.Body.Validate())
	}
	return errs.Err()
}

// ClientInterface is what Client implements: one method per operation, so a test double can
// stand in for the client.
type ClientInterface interface {
	// Record an adoption
	Adopt(ctx context.Context, opts *AdoptRequestOptions) (*Adoption, error)
}

var _ ClientInterface = (*Client)(nil)

// AdoptRequest builds the request of Adopt, with the editors of the client applied.
func (c *Client) AdoptRequest(ctx context.Context, opts *AdoptRequestOptions) (*http.Request, error) {
	if opts == nil {
		opts = &AdoptRequestOptions{}
	}
	b := runtime.NewRequestBuilder(http.MethodPost, "/adoptions")
	switch {
	case opts.Body != nil:
		b.JSONBody(opts.Body, "application/json")
	default:
		return nil, runtime.ErrBodyEmpty
	}
	return c.newRequest(ctx, b)
}

// Record an adoption
//
// Adopt returns the body of a 200 response. A response outside 2xx, or a 2xx the spec
// does not list, comes back as a *runtime.APIError, wrapping the error type of its status when the
// spec documents one.
func (c *Client) Adopt(ctx context.Context, opts *AdoptRequestOptions) (*Adoption, error) {
	req, err := c.AdoptRequest(ctx, opts)
	if err != nil {
		return nil, err
	}
	res, body, err := runtime.Send(c.doer, req, c.timeout)
	if err != nil {
		return nil, err
	}

	var out *Adoption
	if err = runtime.DecodeSuccess(res, body, []runtime.Target{
		{Status: "200", MediaType: "application/json", Dst: &out},
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// AdoptToolInput is the input of the adopt tool: the parameters of the operation.
type AdoptToolInput struct {
	// The request body, sent as application/json.
	Body *Adoption `json:"body"`
}

// MCPTools exposes the operations of the API as MCP tools, each calling the client.
type MCPTools struct {
	client ClientInterface
}

// NewMCPTools returns the tools that call c. A nil c panics here, since the SDK does not recover
// a panic in a tool and the first call would end the server.
func NewMCPTools(c ClientInterface) *MCPTools {
	if c == nil {
		panic("NewMCPTools: nil client")
	}
	return &MCPTools{client: c}
}

// Register adds every tool to s. To add a few, pass the definition and the handler of each to
// mcp.AddTool instead.
func (t *MCPTools) Register(s *mcp.Server) {
	mcp.AddTool(s, t.AdoptTool(), t.Adopt)
}

// AdoptTool is the definition of the adopt tool: its name, its description and the schema
// of its input.
func (t *MCPTools) AdoptTool() *mcp.Tool {
	return &mcp.Tool{
		Name:        "adopt",
		Description: "Record an adoption",
		InputSchema: json.RawMessage(`{"type":"object","properties":{"body":{"$ref":"#/$defs/Adoption"}},"required":["body"],"additionalProperties":false,"$defs":{"Adoption":{"type":"object","properties":{"family":{"type":"string"},"pet":{"anyOf":[{"allOf":[{"$ref":"#/$defs/Pet"}]},{"type":"null"}],"description":"The pet, or null while the family has not chosen one."},"priority":{"anyOf":[{"type":"string","enum":["high","low"]},{"type":"null"}]}},"required":["family"]},"Pet":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}}`),
		Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: false},
	}
}

// Adopt handles the adopt tool: it calls Adopt of the client and answers with what it returns as structured content.
// An error of the client is the error of the tool, with the body of a response outside 2xx.
func (t *MCPTools) Adopt(ctx context.Context, _ *mcp.CallToolRequest, in AdoptToolInput) (*mcp.CallToolResult, any, error) {
	opts := &AdoptRequestOptions{
		Body: in.Body,
	}
	out, err := t.client.Adopt(ctx, opts)
	if err != nil {
		return nil, nil, runtime.ToolError(err)
	}
	return nil, runtime.ToolResult{Value: out}, nil
}
