// Code generated by mockzilla-codegen. DO NOT EDIT.

package anyof

import (
	"time"

	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV2

type Named struct {
	Name string `json:"name"`
}

type Aged struct {
	Age int `json:"age"`
}

type Person struct {
	Named *Named `json:"-"`
	Aged  *Aged  `json:"-"`
}

// MarshalJSON writes the variants that are set.
func (p Person) MarshalJSON() ([]byte, error) {
	var set []any
	if p.Named != nil {
		set = append(set, p.Named)
	}
	if p.Aged != nil {
		set = append(set, p.Aged)
	}
	return runtime.MarshalUnion(nil, set...)
}

// UnmarshalJSON sets the variants data matches.
func (p *Person) UnmarshalJSON(data []byte) error {
	*p = Person{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		IsAnyOf: true,
		Variants: []runtime.Variant{
			{
				Name:     "Named",
				Kind:     runtime.KindObject,
				Required: []string{"name"},
				Known:    []string{"name"},
				Into:     runtime.Into(&p.Named),
			},
			{
				Name:     "Aged",
				Kind:     runtime.KindObject,
				Required: []string{"age"},
				Known:    []string{"age"},
				Into:     runtime.Into(&p.Aged),
			},
		},
	})
}

// Validate checks the value against the constraints of the spec.
func (p Person) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("", runtime.AtLeastOne(p.Named != nil, p.Aged != nil))
	return errs.Err()
}

type Stamp struct {
	Time   *time.Time `json:"-"`
	String *string    `json:"-"`
}

// MarshalJSON writes the variants that are set.
func (s Stamp) MarshalJSON() ([]byte, error) {
	var set []any
	if s.Time != nil {
		set = append(set, s.Time)
	}
	if s.String != nil {
		set = append(set, s.String)
	}
	return runtime.MarshalUnion(nil, set...)
}

// UnmarshalJSON sets the variants data matches.
func (s *Stamp) UnmarshalJSON(data []byte) error {
	*s = Stamp{}
	return runtime.UnmarshalUnion(data, runtime.Union{
		IsAnyOf: true,
		Variants: []runtime.Variant{
			{
				Name: "Time",
				Kind: runtime.KindString,
				Into: runtime.Into(&s.Time),
			},
			{
				Name: "String",
				Kind: runtime.KindString,
				Into: runtime.Into(&s.String),
			},
		},
	})
}
