// Code generated by mockzilla-codegen. DO NOT EDIT.

package scaffolds

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"

	echo "github.com/labstack/echo/v4"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime"
	"github.com/mockzilla/mockzilla-codegen/pkg/runtime/httpserver"
)

// Fails to compile when the runtime does not match the generator that wrote this file.
const _ = runtime.SupportsGeneratorV1

type TodoSchema struct {
	Title string `json:"title"`
	Done  *bool  `json:"done,omitempty"`
}

type ListTodosResponse200 []TodoSchema

// TodoInterface is what the generated handlers call. Implement it with the business logic.
type TodoInterface interface {
	// ListTodos handles GET /todos.
	ListTodos(ctx context.Context, opts *ListTodosServiceRequestOptions) (*ListTodosResponseData, error)
	// CreateTodo handles POST /todos.
	CreateTodo(ctx context.Context, opts *CreateTodoServiceRequestOptions) (*CreateTodoResponseData, error)
}

// ListTodosServiceRequestOptions is what ListTodos receives.
type ListTodosServiceRequestOptions struct {
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *ListTodosServiceRequestOptions) Validate() error {
	return nil
}

// ListTodosResponseData is what ListTodos returns.
type ListTodosResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewListTodosResponseData returns the 200 response with its application/json body.
func NewListTodosResponseData(body ListTodosResponse200) *ListTodosResponseData {
	return &ListTodosResponseData{Status: 200, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *ListTodosResponseData) WithStatus(code int) *ListTodosResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *ListTodosResponseData) WithHeaders(h http.Header) *ListTodosResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *ListTodosResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *ListTodosResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *ListTodosResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *ListTodosResponseData) ContentType() string {
	return r.contentType
}

// CreateTodoServiceRequestOptions is what CreateTodo receives.
type CreateTodoServiceRequestOptions struct {
	// Body sent as application/json.
	Body       *TodoSchema
	RawRequest *http.Request
}

// Validate checks the parameters and the body against the constraints of the spec.
func (o *CreateTodoServiceRequestOptions) Validate() error {
	return nil
}

// CreateTodoResponseData is what CreateTodo returns.
type CreateTodoResponseData struct {
	Status  int
	Headers http.Header
	Body    any

	contentType string
}

// NewCreateTodoResponseData returns the 201 response with its application/json body.
func NewCreateTodoResponseData(body *TodoSchema) *CreateTodoResponseData {
	return &CreateTodoResponseData{Status: 201, Body: body, contentType: "application/json"}
}

// WithStatus sets the status code.
func (r *CreateTodoResponseData) WithStatus(code int) *CreateTodoResponseData {
	r.Status = code
	return r
}

// WithHeaders sets the headers.
func (r *CreateTodoResponseData) WithHeaders(h http.Header) *CreateTodoResponseData {
	r.Headers = h
	return r
}

// StatusCode returns the status.
func (r *CreateTodoResponseData) StatusCode() int {
	return r.Status
}

// Header returns the headers.
func (r *CreateTodoResponseData) Header() http.Header {
	return r.Headers
}

// Payload returns the body.
func (r *CreateTodoResponseData) Payload() any {
	return r.Body
}

// ContentType returns the media type of the body, empty for the default of its Go type.
func (r *CreateTodoResponseData) ContentType() string {
	return r.contentType
}

// The error types the handlers use, as the runtime declares them.
type (
	ErrorKind           = httpserver.ErrorKind
	HandlerError        = httpserver.HandlerError
	ErrorHandler        = httpserver.ErrorHandler
	ErrorHandlerFunc    = httpserver.ErrorHandlerFunc
	DefaultErrorHandler = httpserver.DefaultErrorHandler
)

// The kinds of HandlerError.
const (
	ErrorParse      = httpserver.ErrorParse
	ErrorDecode     = httpserver.ErrorDecode
	ErrorValidation = httpserver.ErrorValidation
	ErrorService    = httpserver.ErrorService
	ErrorResponse   = httpserver.ErrorResponse
)

// ServerOptions is what the adapter and the router are set up with.
type ServerOptions struct {
	Router              any
	Middleware          []func(http.Handler) http.Handler
	OperationMiddleware []func(http.Handler) http.Handler
	ErrorHandler        httpserver.ErrorHandler
	JSONDecoder         func(data []byte, v any) error
	JSONEncoder         func(v any) ([]byte, error)
	MultipartMaxMemory  int64
}

// ServerOption sets one field of ServerOptions.
type ServerOption func(*ServerOptions)

// NewServerOptions applies opts to the defaults.
func NewServerOptions(opts ...ServerOption) *ServerOptions {
	o := &ServerOptions{
		ErrorHandler:       httpserver.DefaultErrorHandler{},
		JSONDecoder:        json.Unmarshal,
		JSONEncoder:        json.Marshal,
		MultipartMaxMemory: 33554432,
	}
	for _, opt := range opts {
		opt(o)
	}
	return o
}

// WithMiddleware wraps the routes with mw, outermost first; on a new router, unknown paths too.
func WithMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.Middleware = append(o.Middleware, mw...)
	}
}

// WithOperationMiddleware wraps each operation with mw, once its name is on the context.
func WithOperationMiddleware(mw ...func(http.Handler) http.Handler) ServerOption {
	return func(o *ServerOptions) {
		o.OperationMiddleware = append(o.OperationMiddleware, mw...)
	}
}

// WithErrorHandler sets what writes the response of a failed request.
func WithErrorHandler(h httpserver.ErrorHandler) ServerOption {
	return func(o *ServerOptions) {
		o.ErrorHandler = h
	}
}

// WithJSONDecoder sets what reads JSON request bodies.
func WithJSONDecoder(decode func(data []byte, v any) error) ServerOption {
	return func(o *ServerOptions) {
		o.JSONDecoder = decode
	}
}

// WithJSONEncoder sets what writes JSON response bodies and stream frames.
func WithJSONEncoder(encode func(v any) ([]byte, error)) ServerOption {
	return func(o *ServerOptions) {
		o.JSONEncoder = encode
	}
}

// WithMultipartMaxMemory sets how much of a multipart form stays in memory.
func WithMultipartMaxMemory(n int64) ServerOption {
	return func(o *ServerOptions) {
		o.MultipartMaxMemory = n
	}
}

// HTTPAdapter answers HTTP requests by calling the service.
type HTTPAdapter struct {
	svc        TodoInterface
	opts       *ServerOptions
	operations httpserver.Chain
}

type responseData interface {
	StatusCode() int
	Header() http.Header
	Payload() any
	ContentType() string
}

// NewHTTPAdapter returns the adapter of svc.
func NewHTTPAdapter(svc TodoInterface, opts ...ServerOption) *HTTPAdapter {
	o := NewServerOptions(opts...)
	return &HTTPAdapter{svc: svc, opts: o, operations: httpserver.NewChain(o.OperationMiddleware...)}
}

// ListTodos handles GET /todos.
func (a *HTTPAdapter) ListTodos(c echo.Context) error {
	a.operations.Serve(c.Response(), c.Request(), "ListTodos", a.serveListTodos)
	return nil
}

func (a *HTTPAdapter) serveListTodos(w http.ResponseWriter, r *http.Request) {
	opts := &ListTodosServiceRequestOptions{RawRequest: r}

	res, err := a.svc.ListTodos(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListTodos", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "ListTodos", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "ListTodos", res)
}

// CreateTodo handles POST /todos.
func (a *HTTPAdapter) CreateTodo(c echo.Context) error {
	a.operations.Serve(c.Response(), c.Request(), "CreateTodo", a.serveCreateTodo)
	return nil
}

func (a *HTTPAdapter) serveCreateTodo(w http.ResponseWriter, r *http.Request) {
	opts := &CreateTodoServiceRequestOptions{RawRequest: r}
	switch contentType := runtime.ContentType(r.Header); contentType {
	case "application/json":
		if err := runtime.DecodeJSON(r.Body, &opts.Body, true, a.opts.JSONDecoder); err != nil {
			a.failDecode(w, r, "CreateTodo", err)
			return
		}
	case "":
		a.failDecode(w, r, "CreateTodo", runtime.ErrBodyEmpty)
		return
	default:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: "CreateTodo", Status: http.StatusUnsupportedMediaType, Err: runtime.ContentTypeError(contentType)})
		return
	}

	res, err := a.svc.CreateTodo(r.Context(), opts)
	if err != nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateTodo", Err: err})
		return
	}
	if res == nil {
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: "CreateTodo", Err: httpserver.ErrNoResponse})
		return
	}
	a.write(w, r, "CreateTodo", res)
}

func (a *HTTPAdapter) fail(w http.ResponseWriter, r *http.Request, err *httpserver.HandlerError) {
	// A response that failed to write leaves its media type, which is not the error's.
	w.Header().Del("Content-Type")
	a.opts.ErrorHandler.HandleError(w, r, err.StatusCode(), err)
}

func (a *HTTPAdapter) failDecode(w http.ResponseWriter, r *http.Request, id string, err error) {
	a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorDecode, OperationID: id, Err: err})
}

func (a *HTTPAdapter) write(w http.ResponseWriter, r *http.Request, id string, res responseData) {
	if res.ContentType() != "" {
		w.Header().Set("Content-Type", res.ContentType())
	}
	err := httpserver.Writer{Marshal: a.opts.JSONEncoder}.Write(w, res.StatusCode(), res.Header(), res.Payload())
	switch {
	case errors.Is(err, runtime.ErrContentType):
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorResponse, OperationID: id, Err: err})
	case err != nil:
		a.fail(w, r, &httpserver.HandlerError{Kind: httpserver.ErrorService, OperationID: id, Err: err})
	}
}

// WithRouter registers the routes on e instead of a new Echo.
func WithRouter(e *echo.Echo) ServerOption {
	return func(o *ServerOptions) {
		o.Router = e
	}
}

// NewRouter registers every operation on an Echo.
func NewRouter(svc TodoInterface, opts ...ServerOption) *echo.Echo {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	middleware := make([]echo.MiddlewareFunc, len(o.Middleware))
	for i, mw := range o.Middleware {
		middleware[i] = echo.WrapMiddleware(mw)
	}
	register := func(e *echo.Echo, m ...echo.MiddlewareFunc) {
		e.GET("/todos", a.ListTodos, m...)
		e.POST("/todos", a.CreateTodo, m...)
	}

	e, _ := o.Router.(*echo.Echo)
	if e == nil {
		e = echo.New()
		if len(middleware) > 0 {
			e.Use(append(middleware, answerErrors)...)
		}
		register(e)
		return e
	}
	register(e, middleware...)
	return e
}

func answerErrors(next echo.HandlerFunc) echo.HandlerFunc {
	return func(c echo.Context) error {
		if err := next(c); err != nil {
			// Answered here, inside the middleware, so the middleware sees the response.
			c.Error(err)
		}
		return nil
	}
}
