// Code generated by mockzilla-codegen. DO NOT EDIT.

package readwrite

import "github.com/mockzilla/mockzilla-codegen/pkg/runtime"

// Fails to compile when the runtime package does not match the mockzilla-codegen version that
// wrote this file.
const _ = runtime.SupportsGeneratorV2

type User struct {
	ID       string   `json:"id,omitempty"`
	Name     string   `json:"name"`
	Password string   `json:"password,omitempty"`
	Roles    []string `json:"roles,omitempty"`
}

// Validate checks the value against the constraints of the spec, as a request carries it.
func (u User) Validate() error {
	var errs runtime.ValidationErrors
	errs.Append("name", runtime.MinLength(u.Name, 1))
	errs.Append("password", runtime.MinLength(u.Password, 8))
	return errs.Err()
}

// ValidateResponse checks the value against the constraints of the spec, as a response carries it.
func (u User) ValidateResponse() error {
	var errs runtime.ValidationErrors
	errs.Append("id", runtime.Format(u.ID, "uuid"))
	errs.Append("name", runtime.MinLength(u.Name, 1))
	if u.Roles == nil {
		errs.Add("roles", "is required")
	}
	return errs.Err()
}

type Team struct {
	Lead *User `json:"lead,omitempty"`
}

// Validate checks the value against the constraints of the spec, as a request carries it.
func (t Team) Validate() error {
	var errs runtime.ValidationErrors
	if t.Lead != nil {
		errs.Append("lead", t.Lead.Validate())
	}
	return errs.Err()
}

// ValidateResponse checks the value against the constraints of the spec, as a response carries it.
func (t Team) ValidateResponse() error {
	var errs runtime.ValidationErrors
	if t.Lead != nil {
		errs.Append("lead", t.Lead.ValidateResponse())
	}
	return errs.Err()
}
