// Code generated by mockzilla-codegen. DO NOT EDIT.

package api

import khttp "github.com/go-kratos/kratos/v2/transport/http"

// WithRouter registers the routes on s instead of a new Server.
func WithRouter(s *khttp.Server) ServerOption {
	return func(o *ServerOptions) {
		o.Router = s
	}
}

// NewRouter registers every operation on a kratos HTTP server.
func NewRouter(svc BooksInterface, opts ...ServerOption) *khttp.Server {
	o := NewServerOptions(opts...)
	a := NewHTTPAdapter(svc, opts...)
	filters := make([]khttp.FilterFunc, len(o.Middleware))
	for i, mw := range o.Middleware {
		filters[i] = mw
	}
	register := func(r *khttp.Router) {
		r.GET("/books/{isbn}", a.GetBook)
	}

	if s, _ := o.Router.(*khttp.Server); s != nil {
		register(s.Route("/", filters...))
		return s
	}
	// Without these, kratos ends each request after 1s and serves http.DefaultServeMux.
	s := khttp.NewServer(khttp.Filter(filters...), khttp.Timeout(0), khttp.NotFoundHandler(nil), khttp.MethodNotAllowedHandler(nil))
	register(s.Route("/"))
	return s
}
