// Code generated by mockzilla-codegen. DO NOT EDIT.

package jsonignore

type Session struct {
	ID    *string       `json:"id,omitempty"`
	Cache *SessionCache `json:"-"`
}

type SessionCache struct {
	Hits *int `json:"hits,omitempty"`
}
